<?php

?>
<form action="<?= $this->url('settings/notification-hours', ['action' => 'save']) ?>" method="post">
    <div class="row">
        <div class="col-xl-6">
            <?php
            /** @var \Settings\Entity\NotificationHour $hour */
            foreach ($this->hours as $hour):
                $date = new \DateTime("last sunday");
                $date->modify($hour->getDay() . ' days');
                ?>
                <div class="row align-items-center mb-2">
                    <div class="col"><?= $this->dateFormat($date, IntlDateFormatter::NONE, IntlDateFormatter::NONE, 'pl_PL', 'EEEE') ?></div>
                    <div class="col">
                        <input
                                type="time"
                                name="from[<?= $hour->getId() ?>]"
                                value="<?= $hour->getFrom()->format("H:i") ?>"
                                class="form-control"
                        >
                    </div>
                    <div class="col">
                        <input
                                type="time"
                                name="to[<?= $hour->getId() ?>]"
                                value="<?= $hour->getTo()->format("H:i") ?>"
                                class="form-control"
                        >
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <button type="submit" class="btn btn-primary d-block ms-auto mt-2"><?= $this->translate('Zapisz') ?></button>
</form>