<p>
    Dostępne znaczniki: <br/>
    <code>
        <?php
        $tagNames = [];
        foreach ($this->tags as $tag) {
            $tagNames[] = sprintf("[%s]", $tag);
        }
        echo implode(", ", $tagNames);
        ?>
    </code>
</p>

<?=$this->form($this->form, null) ?>

<?php
$tags = \Laminas\Json\Json::encode($this->tags);
$this->headLink()->appendStylesheet($this->basePath('bower_components/summernote/dist/summernote.css'));
$this->headScript()->appendFile($this->basePath('bower_components/summernote/dist/summernote.js'));
$this->headScript()->appendFile($this->basePath('js/summernote/summernote-' . Locale::getDefault() . '.js'));

$this->inlineScript()->captureStart();
echo <<<JS
    $(function() {
        $('.summernote').summernote({
            height: 100,
            lang: gLocale,
            hint: {
                words: {$tags},
                match: /\b(\w{1,})$/,
                search: function (keyword, callback) {
                    callback($.grep(this.words, function (item) {
                        return item.indexOf(keyword) === 0;
                    }));
                },
                content: function(item) {
                    return "[" + item + "]";
                }
            }
        });
    });
JS;
$this->inlineScript()->captureEnd();
?>

