<?php

namespace Hr\Repository;

/**
 * AdditionalPageContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdditionalPageContentRepository extends \Doctrine\ORM\EntityRepository
{
}
