<?= $this->urlParam('action') == 'edit' ? $this->partial('customers/tabs') : '' ?>
<?php
$this->form->setOption('layout', \TwbsHelper\Form\View\Helper\Form::LAYOUT_HORIZONTAL);
?>
<?= $this->formSl($this->form, 'horizontal', 2) ?>

<?php

$autocompleteValues = $this->json($this->autocomplete_values ?? []);
$autocompletePayer = $this->json($this->autocomplete2 ?? []);

$this->headScript()->appendFile($this->basePath('js/min/customers.js'));

$this->inlineScript()->captureStart();
echo <<<JS
    let map;

    $(function() {
        const autocompleteData = {$autocompleteValues};
        const autocompPayer = {$autocompletePayer}
  
        new AutocompleteSingle('city', '{$this->url('autocomplete/dictionary', ['dictionary' => \Hr\Entity\Dictionary::DIC_CITIES])}', autocompleteData);
        new AutocompleteSingle('payer','{$this->url('autocomplete/payer')}', autocompPayer)
        new Autocomplete('customerGroups');
        new ComplexDictionary('format');
        new ComplexDictionary('size');
        new ComplexDictionary('chain');
        Utils.initExtendDictionaryButtons();
        Utils.initExtendPayerButtons();
        
        $("#customerEditForm").submit(function() {
            $(":input[disabled]").prop('disabled', false);
        });
    });
JS;

if ($this->urlParam('id')) {
    echo <<<JS
const customers = new Customers()
customers.initForm()
JS;
}

$this->inlineScript()->captureEnd();
?>