<?= $this->doctype() ?>
<?php
$locale = 'pl';
?>
<html lang="<?= $locale ?>">
<head>
    <meta charset="utf-8">
    <?php if (isset($this->custom_title) && !empty($this->custom_title)) : ?>
        <?= $this->headTitle($this->custom_title)->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php else : ?>
        <?= $this->headTitle($this->translate('HR'))->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php endif; ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <?php
    if (!empty($this->custom_css)) {
        foreach ($this->custom_css as $css) {
            $this->headLink()->appendStylesheet($this->basePath("css/custom/$css"));
        }
    }
    ?>

    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/' . $this->custom_favico ?? 'favicon.ico'])
        ->prependStylesheet($this->basePath('dist/bundle.css'))
        ->prependStylesheet($this->basePath('node_modules/@eonasdan/tempus-dominus/dist/css/tempus-dominus.min.css'))
        ->prependStylesheet($this->basePath('node_modules/@pnotify/core/dist/PNotify.css'))
        ->prependStylesheet($this->basePath('node_modules/@pnotify/core/dist/BrightTheme.css'))
        ->prependStylesheet($this->basePath('node_modules/select2-bootstrap-5-theme/dist/select2-bootstrap-5-theme.min.css'))
        ->prependStylesheet($this->basePath('node_modules/select2/dist/css/select2.min.css'))
        ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css')
        ->prependStylesheet('https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css')
        ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css')
    ?>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">

    <script>
        const gLocale = '<?=$this->locale ?>'
        const gLanguage = '<?=Locale::getDefault() ?>'
        const gIsMobile = <?=$this->mobileDetect()->isMobile() ? 'true' : 'false' ?>
    </script>

    <?= $this->headScript()
        ->prependFile($this->basePath('dist/app.js'))
        ->prependFile($this->basePath('lib/jquery.mask.min.js'))
        ->prependFile($this->basePath('lib/jquery.uploadifive.js'))
//        ->prependFile($this->basePath('node_modules/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js'))
//        ->prependFile($this->basePath('node_modules/@pnotify/core/dist/PNotify.js'))
        ->prependFile($this->basePath('node_modules/select2/dist/js/i18n/pl.js'))
        ->prependFile($this->basePath('node_modules/select2/dist/js/select2.min.js'))
        ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/5.5.2/bootbox.min.js')
        ->prependFile('https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js')
        ->prependFile($this->basePath('node_modules/jquery/dist/jquery.min.js'))
    ?>

    <script>
        bootbox.setDefaults({
            locale: '<?=$locale ?>'
        });

        // datepicker
        $(function () {
            Utils.initDOM(gLocale);
        });
    </script>

    <?= $this->custom_script_head ?>
</head>
<body>
<style>
    <?php $logo = (empty($this->logo)) ? 'empty_logo.png' : $this->logo ?>
    .client-logo {
        background-image: url(<?= $this->basePath('img/mandant_logo/' .$logo) ?>);
        -webkit-background-size: contain;
        background-size: contain;
        background-repeat: no-repeat;
    }
</style>
<div id="bodyLoadingOverlay"></div>
<div id="right-sidebar">
    <span class="pull-right right-sidebar-close"><?= $this->fontAwesome('close') ?></span>
</div>
<div id="overlay"></div>
<div class="wrapper">
    <?= $this->partial('layout/header') ?>
    <?= $this->partial('layout/menu') ?>

    <div
            class="site-container<?= ($this->mobileDetect()->isMobile()) ? ' fn' : ' menu-on desk-container' ?>"
            id="content"
    >
        <?php if ($this->mobileDetect()->isMobile()) : ?>

            <header class="mobile-main-header">
                <div class="mobile-header">
                    <?php if ($this->acl()->getAcl()->isAllowed($this->identity()['configurationPositionId'], Hr\Acl\AclService::HEADER_SL_PIZZA)) : ?>
                        <a href="/" class="logo-pizza sl-pizza header-logo"><img
                                    class="pizza-img pizza-mobi"
                                    src="<?= $this->basePath('img/' . $this->settings_logo_small) ?>"
                            /> </a>
                    <?php endif; ?>

                    <?php if ($this->acl()->getAcl()->isAllowed($this->identity()['configurationPositionId'], Hr\Acl\AclService::HEADER_BREADCRUMB)) : ?>
                        <div class="mobile-breadcrump fl">
                            <h5>
                                <span><?= $this->breadcrumbs() ?></span>
                            </h5>
                        </div>
                    <?php else : ?>
                        <?php if ($this->acl()->getAcl()->isAllowed($this->identity()['configurationPositionId'], Hr\Acl\AclService::HEADER_SL_LOGO)) : ?>
                            <a href="/"><img
                                        src="<?= $this->basePath('img/' . $this->settings_logo) ?>"
                                        class="logo-mobile-client pull-left"
                                /> </a>
                        <?php endif; ?>
                    <?php endif; ?>


                    <?= $this->partial('triple-dot-menu') ?>
                    <?= $this->placeholder('top-right-menu') ?>

                    <?php if ($this->acl()->getAcl()->isAllowed($this->identity()['configurationPositionId'], Hr\Acl\AclService::HEADER_CLIENT_LOGO)) : ?>
                        <div class="client-logo pull-right">
                        </div>
                    <?php endif; ?>
                </div>
            </header>
        <?php endif; ?>
        <div class="row">
            <div class="col-md-12"><?= $this->fm() ?></div>
        </div>

        <div class="addresbar text-center">
            <?= $this->placeholder('addressBar') ?>
        </div>

        <?= $this->content ?>
        <?php if ($this->mobileDetect()->isMobile()) : ?>
            <a href="#" id="back-to-top" title="Back to top">&uarr;</a>
        <?php endif; ?>
    </div>
</div>

<?= $this->inlineScript() ?>
</body>
</html>