<?= $this->doctype() ?>
<html lang="<?= $this->locale ?>">
<head>
    <meta charset="utf-8">
    <?php if (isset($this->custom_title) && !empty($this->custom_title)) : ?>
        <?= $this->headTitle($this->custom_title)->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php else : ?>
        <?= $this->headTitle($this->translate('HR'))->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php endif; ?>
    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/' . $this->custom_favico ?? 'favicon.ico'])
        ->prependStylesheet($this->basePath('dist/bundle.css'))
        ->prependStylesheet('https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css')
    ?>
    <script>
        const gLocale = '<?=$this->locale ?>'
        const gLanguage = '<?=Locale::getDefault() ?>'
        const gIsMobile = <?=$this->mobileDetect()->isMobile() ? 'true' : 'false' ?>
    </script>
    <?= $this->headScript()
        ->prependFile('https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js')
        ->prependFile($this->basePath('node_modules/jquery/dist/jquery.min.js'))
    ?>

    <?= $this->custom_script_head ?>
</head>
<body style="background-color: #f4f7f9;" id="top">
<div id="bodyLoadingOverlay"></div>
<div class="login-site">
    <?php if (isset($this->custom_login_icon) && !empty($this->custom_login_icon)) : ?>
        <div class="login-logo">
            <?php if (isset($this->custom_login_href) && !empty($this->custom_login_href)) : ?>
                <a href="<?= $this->custom_login_href ?>">
                    <img
                            src="<?= $this->basePath('img/' . $this->custom_login_icon) ?>"
                            alt="logo klienta"
                            class="login-logo-img"
                    >
                </a>
            <?php else : ?>
                <img
                        src="<?= $this->basePath('img/' . $this->custom_login_icon) ?>"
                        alt="logo klienta"
                        class="login-logo-img"
                >
            <?php endif; ?>
        </div>
    <?php endif ?>
    <div class="container-fluid">
        <div class="row justify-content-md-center margin-rmv">
            <div class="col col-md-6 col-lg-4"><?= $this->fm() ?></div>
        </div>
    </div>

    <?= $this->content ?>

</div>
</body>
</html>