<div class="row">
    <div class="col-md-12">
        <?=$this->operations([
            [
                'icon' => 'plus',
                'label' => 'dodaj',
                'route' => 'notifications/add',
//                'resource' => 'documentTemplates',
                'mode' => 'add'
            ],
        ]) ?>
    </div>
</div>

<?=$this->searchForm($this->search) ?>

<?=$this->table($this->table, 'notifications', 'notifications') ?>
