<?=$this->partial('customers/tabs')?>

<table class="table">
    <thead>
        <tr>
            <th><?=$this->translate('Pytanie') ?></th>
            <th><?=$this->translate('Odpowiedź') ?></th>
            <th><?=$this->translate('Użytkownik') ?></th>
            <th><?=$this->translate('Data dodania') ?></th>
            <th><?=$this->translate('Wypełniający') ?></th>
        </tr>
    </thead>
    <tbody>
    <?php /** @var \Customers\Entity\AdditionalInformation $information */
        foreach ($this->informations as $information):
            $value = $information->getValue();

            if (strstr($value, 'file:')) {
                $url = $this->url(
                    'customers/additional-informations',
                    ['action' => 'download', 'type' => $this->urlParam('type'), 'id' => $information->getId()],
                );
                $display = "<a href='$url'>pobierz</a>";
            } else {
                $display = $value;
            }
    ?>
            <tr>
                <td><?=$information->getName() ?></td>
                <td><?=$display ?></td>
                <td><?=$information->getUser() ? $information->getUser()->getFullName() : '-' ?></td>
                <td><?=$this->dt($information->getCreationDate()) ?></td>
                <td><?=$information->getCreatingUser()->getFullName() ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>