<?php if (!$this->mobileDetect()->isMobile()) : ?>
    <header class="main-header">
        <div class="navbar-static-top" role="navigation">
            <div class="sl-hamburger">
                <a href="#" class="sidebar-toggle" id="sidebar-toggle">
                    <i class="fa fa-lg fa-bars" data-toggle="main-sidebar" style="vertical-align: -17px"></i>
                </a>
            </div>
            <a href="/" class="logo sl-logo header-logo">
                <img src="<?= $this->basePath('img/' . $this->settings_logo) ?>"/>
            </a>
            <div class="navbar-center fl">
                <h1>
                    <span><?= $this->breadcrumbs() ?></span>
                </h1>
            </div>
        </div>
    </header>
<?php else : ?>

<?php endif; ?>