<?php

if (!$this->mobileDetect()->isMobile()) : ?>
    <aside class="main-sidebar">
        <div class="side">
            <div class="side-scroll">
                <ul class="sidebar-menu">
                    <?php if (!is_null($this->identity())) : ?>
                        <?php if ($this->acl()->getAcl()->isAllowed($this->identity()['configurationPositionId'], Hr\Acl\AclService::MENU_AVATAR)) : ?>
                            <li class="sidebar-menu-header">
                                <img src="<?= $this->basePath('img/default_avatar.png') ?>" style="max-width:75px" class="img-circle" /><br />
                                <?= $this->identity()['name'] ?> <?= $this->identity()['surname'] ?>
                            </li>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?= $this->tikrowMenu([
                        'version' => $this->version,
                    ]) ?>
                </ul>
            </div>
        </div>
    </aside>
<?php else : ?>
    <a href="#" class="mobile-menu-hamburger"><i class="fa fa-bars fa-2x mobile-menu-icon"></i></a>
    <aside class="mobile-sidebar">
        <div class="mobile-menu">
            <ul class="mobile-menu-list">
                <li class="mobile-menu-header">
                    <span class="mobile-menu-close"><?= $this->fontAwesome('close') ?></span>
                    <?php if ($this->acl()->getAcl()->isAllowed($this->identity()['configurationPositionId'], Hr\Acl\AclService::MENU_AVATAR)) : ?>
                        <img src="<?= $this->basePath('img/default_avatar.png') ?>" style="max-width:75px" class="img-circle" /><br />
                        <?= $this->identity()['name'] ?> <?= $this->identity()['surname'] ?>
                    <?php endif; ?>
                </li>

                <?= $this->tikrowMenu([
                    'version' => $this->version,
                ]) ?>
            </ul>
        </div>
    </aside>
<?php endif; ?>