<?php if (!$this->mobileDetect()->isMobile()) :  ?>
    <?php foreach ($this->container as $page): ?>
        <?php if ($this->navigation()->accept($page)): ?>
            <?php
                $label = $page->getLabel();
                if ($icon = $page->get('icon')) {
                    $icon = $this->fontAwesome($icon);
                    $label = $icon . ' ' . $label;
                }
            ?>

            <?php if ($page->hasPages()): ?>
                <li class="menu dropdown mega-dropdown">
                    <a href="#" class="tree-toggle">
                        <?=$label ?>
                        <i class="fa fa-angle-left fa-lg pull-right"></i>
                    </a>

                    <ul class="tree">
                        <?php foreach ($page->getPages() as $subpage): ?>
                            <?php if ($this->navigation()->accept($subpage)): ?>
                                <?php $subpage->set('icon', '');
                                try {
                                    $subpage->getHref();
                                } catch (\Laminas\Router\Exception\InvalidArgumentException $e) {
                                    continue;
                                }
                                ?>
                                <li class="tree-node">
                                    <?=$this->partial('partials/user-menu-link', ['page' => $subpage]) ?>
                                </li>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </ul>
                </li>
            <?php else: ?>
                <?php
                try {
                    $page->getHref();
                } catch (\Laminas\Router\Exception\InvalidArgumentException $e) {
                    continue;
                }
                ?>
                <li class="menu">
                    <?=$this->partial('partials/user-menu-link', ['page' => $page]) ?>
                </li>
            <?php endif; ?>
        <?php endif; ?>
    <?php endforeach; ?>
<?php else : ?>
    <?php foreach ($this->container as $page) : ?>
        <?php if ($this->navigation()->accept($page)) : ?>
            <?php if ($page->hasPages()) : ?>
                <?php $first = true; ?>
                <?php foreach ($page->getPages() as $subpage): ?>
                    <?php if ($this->navigation()->accept($subpage)): ?>
                        <?php
                        try {
                            $subpage->getHref();
                        } catch (\Laminas\Router\Exception\InvalidArgumentException $e) {
                            continue;
                        }
                        if (!$subpage->get('icon') && $page->get('icon')) {
                            $subpage->set('icon', $page->get('icon'));
                        }
                        ?>
                        <li class="mobile-menu-position <?=(!$first) ? '' : 'first-item' ?>">
                            <?=$this->partial('partials/user-menu-link', ['page' => $subpage]) ?>
                        </li>
                        <?php $first = false; ?>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php else : ?>
                <?php
                try {
                    $page->getHref();
                } catch (\Laminas\Router\Exception\InvalidArgumentException $e) {
                    continue;
                }
                ?>
                <li class="mobile-menu-position first-item">
                    <?=$this->partial('partials/user-menu-link', ['page' => $page]) ?>
                </li>
            <?php endif; ?>
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>