<form action="" class="form-search">
    <input type="hidden" name="perPage" value="<?=$this->urlParam('perPage') ?>">
</form>

<div class="row">
    <div class="col-md-12">
        <?=$this->operations([
            [
                'icon' => 'plus',
                'label' => 'dodaj',
                'route' => 'users/invites',
                'params' =>  [
                    'action' => 'add',
                ],
            ],
        ]) ?>
    </div>
</div>

<?=$this->table($this->table, 'users/invites') ?>