<?php
$this->search->setAttribute('action', $this->url('customers/picker'));
echo $this->searchForm($this->search);
$autocompleteValues = $this->json($this->autocomplete_values ?? []);
?>

<?= $this->table($this->table, 'customers/picker') ?>

<script>
    autocompleteData = <?=$autocompleteValues ?>;

    new AutocompleteSingle('city', '<?=$this->url('autocomplete/dictionary', ['dictionary' => \Hr\Entity\Dictionary::DIC_CITIES]) ?>', autocompleteData, '.modal-body');
    new Autocomplete('chain');
    new Autocomplete('visitsFrequency');
    new Autocomplete('region');
    new Autocomplete('size');
    new Autocomplete('priority');
    new Autocomplete('format');
    new Autocomplete('logisticRegion');
    new Autocomplete('creator');
    new Autocomplete('subsizes');
    new Autocomplete('subchain');
    new Autocomplete('subformats');
    new Autocomplete('saleStage');
    new Autocomplete('customerStatus');
</script>
