<p>
    Dostępne znaczniki: <br/>
    <code>
        <?php
            $tagNames = [];
            foreach ($this->tags as $tag) {
                $tagNames[] = sprintf("[%s]", $tag);
            }
            echo implode(", ", $tagNames );
        ?>
    </code>
</p>
<p>Dodatkowo akceptowane są znaczniki zawierające wartość <em>key</em> z tabeli <em>userData</em>.</p>

<?=$this->form($this->form, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL) ?>

<?php
$tags = \Laminas\Json\Json::encode($this->tags);
$this->headLink()->appendStylesheet($this->basePath('bower_components/summernote/dist/summernote.css'));
$this->headScript()->appendFile($this->basePath('bower_components/summernote/dist/summernote.js'));
$this->headScript()->appendFile($this->basePath('js/summernote/summernote-pl.js'));

$this->inlineScript()->captureStart();
echo <<<JS
    function addSummernote() {
        $('#notification-content').summernote({
                height: 500,
                lang: 'pl',
                hint: {
                    words: {$tags},
                    match: /\b(\w{1,})$/,
                    search: function (keyword, callback) {
                        callback($.grep(this.words, function (item) {
                            return item.indexOf(keyword) === 0;
                        }));
                    },
                    content: function(item) {
                        return "[" + item + "]";
                    }
                }
            })
    }
    
    function isSms() {
        const type = $('#notification-type option:selected').text()
        
        return type.includes('SMS - ')
    }
    
    $(function() {
        if (!isSms()) {
            addSummernote()
        }
        
        $('#notification-type').change(() => {
            if (isSms()) {
                $('#notification-content').summernote('destroy')
            } else {
                addSummernote()
            }
        })
    });
JS;
$this->inlineScript()->captureEnd();
?>
