<?php

use Customers\Entity\UserRelationJoint;

?>
<?= $this->partial('customers/tabs') ?>

<div class="row mb-10">
    <div class="col-md-12">
        <?= $this->operations([
            [
                'icon' => 'link',
                'label' => 'dodaj relację',
                'route' => 'customers/users',
                'params' => [
                    'action' => 'add',
                    'id' => $this->urlParam('id'),
                ],
            ],
            [
                'icon' => 'plus',
                'label' => 'dodaj użytkownika',
                'route' => 'customers/users',
                'params' => [
                    'action' => 'add-user',
                    'id' => $this->urlParam('id'),
                ],
            ],
            [
                'icon' => 'undo',
                'label' => 'powrót',
                'route' => 'customers/users',
                'class' => 'go-back',
            ],
        ]) ?>
    </div>
</div>

<div class="table-responsive">
    <table class="table table-condensed">
        <thead>
        <tr>
            <th><?= $this->translate('Imię i nazwisko') ?></th>
            <th><?= $this->translate('Uprawnienia') ?></th>
            <th><?= $this->translate('Stanowisko') ?></th>
            <th><?= $this->translate('Email') ?></th>
            <th><?= $this->translate('Telefon') ?></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php /** @var UserRelationJoint $user */
        foreach ($this->users as $user): ?>
            <tr>
                <td><?= $user->getUser()->getFullName() ?></td>
                <td><?= $user->getRelation()->getName() ?></td>
                <td><?= $user->getUser()->getConfigurationPosition() ? $user->getUser()->getConfigurationPosition()->getName() : '-' ?></td>
                <td>
                    <a href="mailto:<?= $user->getUser()->getEmail() ?>"><?= $this->fontAwesome('envelope-o') ?> <?= $user->getUser()->getEmail() ?></a>
                    <?php if ($user->getUser()->getConfigurationPosition()->getKey() == \Configuration\Entity\Position::POSITION_CRM_CUSTOMER): ?>
                        <a
                            href="<?= $this->url('customers/users', ['action' => 'email', 'id' => $user->getUser()->getId()]) ?>"
                            class="a-edit-user"
                            data-value="<?= $user->getUser()->getEmail() ?>"
                        ><?= $this->fontAwesome('pencil') ?></a>
                    <?php endif; ?>
                </td>
                <td>
                    <a href="tel:<?= $user->getUser()->getPhonenumber() ?>"><?= $this->fontAwesome('mobile') ?> <?= $user->getUser()->getPhonenumber() ?></a>
                    <?php if ($user->getUser()->getConfigurationPosition()->getKey() == \Configuration\Entity\Position::POSITION_CRM_CUSTOMER): ?>
                        <a
                            href="<?= $this->url('customers/users', ['action' => 'phone', 'id' => $user->getUser()->getId()]) ?>"
                            class="a-edit-user"
                            data-value="<?= $user->getUser()->getPhonenumber() ?>"
                        ><?= $this->fontAwesome('pencil') ?></a>
                    <?php endif; ?>
                </td>
                <td>
                    <a href="<?= $this->url('customers/users', ['action' => 'edit', 'id' => $user->getId()]) ?>"><?= $this->fontAwesome('pencil') ?></a>
                    <a
                        href="<?= $this->url('customers/users', ['action' => 'delete', 'id' => $user->getId()]) ?>"
                        class="a-delete"
                    ><?= $this->fontAwesome('trash') ?></a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<script>
    $(function () {
        let content = $("#content")
        content.off("click")

        content.on("click", ".a-delete", function (event) {
            event.preventDefault()
            const href = $(this).attr('href')
            bootbox.confirm({
                message: 'Czy na pewno chcesz usunąć rekord?',
                buttons: {
                    cancel: {label: 'Anuluj'},
                    confirm: {label: 'Usuń'}
                },
                callback: function (result) {
                    if (result) {
                        $.post(href, function (resp) {
                            if (resp === 'ok') {
                                $("#content").load(location.href)
                            }
                        })
                    }
                }
            })

            return false
        })

        content.on("click", ".a-edit-user", function (e) {
            e.preventDefault()

            const a = $(e.currentTarget)

            bootbox.prompt({
                title: t.t('Edytuj wartość'),
                inputType: 'text',
                value: a.data('value'),
                callback: async (resp) => {
                    if (resp) {
                        await $.post(a.attr('href'), {value: resp})
                        await $("#content").load(location.href)
                        bootbox.hideAll()
                    }
                }
            })
        })
    })
</script>