<?php

namespace DocumentTemplates\Repository;

use Hr\Repository\BaseRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends BaseRepository
{
}