<div class="row">
    <div class="col-md-12">
        <?=$this->operations([
            [
                'icon' => 'plus',
                'label' => 'dodaj',
                'route' => 'users/blocked-data',
                'params' =>  [
                    'action' => 'add',
                ],
            ],
        ]) ?>
    </div>
</div>

<?=$this->searchForm($this->search) ?>

<?=$this->table($this->table, 'users/blocked-data') ?>

<?php
$this->headScript()->appendFile($this->basePath('js/min/user.js'));
$this->inlineScript()->captureStart();
echo <<<JS
    $(function() {
        $("body").on("click", ".a-remove", (e) => {
            const href = $(e.currentTarget).attr('href')
            
            bootbox.confirm(t.t('Czy na pewno chcesz usunąć rekord?'), (resp) => {
                if (resp) {
                    $.post(href, (r) => {
                        if (r == 'ok') {
                            new NotifySuccess('Rekord został usunięty')
                            $("#content").load(location.href)
                        } else {
                            new NotifyError()
                        }
                    })
                }
            })
            
            return false
        });
    });
JS;
$this->inlineScript()->captureEnd();
?>