<?php $url = '#'; ?>
<div class="row">
    <div class="col-md-12">
        <?php if (!is_null($this->identity())): ?>
            <h3 class="text-center font-bold"><?= $this->translate('Witamy w systemie') ?>,&thinsp;<?= $this->identity()['name'] ?>&nbsp;<?= $this->identity()['surname'] ?>!</h3>
        <?php endif; ?>
        <div class="shortcut-content">
            <div style="margin:0 auto">
                <?php if ($this->menu): ?>
                    <?php foreach ($this->menu as $m) : ?>
                        <?php if ($this->acl()->getAcl()->isAllowed($this->identity()['configurationPositionId'], $m->getName())) : ?>
                            <?php
                            if (empty($m->getRoute())) {
                                $url = '#';
                            } else {
                                $url = $m->getRoute();
                            }
                            ?>
                            <a href="<?= $url ?>" class="shortcut-link">
                            <span class="shortcut-icon">
                                <i class="fa fa-<?= $m->getIcon() ?> fa-2x" aria-hidden="true"></i>
                            </span>
                                <span class="shortcut-title"><?= $m->getLabel() ?></span>
                            </a>
                        <?php endif ?>
                    <?php endforeach; ?>
                <?php endif; ?>

                <div class="clearfix"></div>
            </div>
        </div>
        <?php if ($this->content): ?>
            <?php foreach ($this->content as $c): ?>
                <div><?= $c->getContent() ?></div>
            <?php endforeach; ?>
        <?php endif; ?>

    </div>
</div>
