<style>
    .tikrow-radio {
        width: 150px;
    }
</style>

<?php $this->form->get('login')->setAttribute('placeholder', 'Login'); ?>
<div class="row justify-content-md-center margin-rmv">
    <div class="col col-md-6 col-lg-4 ">
        <div class="login">
            <p class="login-title"><?= $this->translate('ZALOGUJ SIĘ') ?></p>
            <div class="login-form">
                <?= $this->form($this->form, null) ?>
            </div>
        </div>
    </div>
</div>