<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tikrow</title>
    <link rel="stylesheet" href="./css/bootstrap/bootstrap.min.css">
    <link rel="stylesheet" href="./css/splash.css">
    <link rel="apple-touch-icon-precomposed" sizes="57x57" href="./favicons/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="./favicons/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="./favicons/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="./favicons/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon-precomposed" sizes="60x60" href="./favicons/apple-touch-icon-60x60.png">
    <link rel="apple-touch-icon-precomposed" sizes="120x120" href="./favicons/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon-precomposed" sizes="76x76" href="./favicons/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon-precomposed" sizes="152x152" href="./favicons/apple-touch-icon-152x152.png">
    <link rel="icon" type="image/png" href="./favicons/favicon-196x196.png" sizes="196x196">
    <link rel="icon" type="image/png" href="./favicons/favicon-96x96.png" sizes="96x96">
    <link rel="icon" type="image/png" href="./favicons/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="./favicons/favicon-16x16.png" sizes="16x16">
    <link rel="icon" type="image/png" href="./favicons/favicon-128.png" sizes="128x128">

    <script>
        window.dataLayer = window.dataLayer || [];
        window.dataLayer.push({
            originalLocation: document.location.protocol + '//' +
            document.location.hostname +
            document.location.pathname +
            document.location.search
        });
    </script>

    <script>
        window.dataLayer = window.dataLayer || [];
        dataLayer.push({
            'event': 'virtualPageview',
            'virtualPageURL': '/login',
            'virtualPageTitle': 'Tikrow',
            'pageType' : 'tikrow.com',
            'userStatus' : 'Niezalogowany',
            'userType' : '',
            'userId' : ''
        });
    </script>

    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-PVSC2XR');</script>
    <!-- End Google Tag Manager -->

</head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PVSC2XR"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

<div class="main-page">
    <div class="coverHolder">
        <div class="main-page-logo col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 text-center">
            <img src="images/logoTikrow-light.svg" class="img-fluid mainLogo" />
        </div>

        <div class="row main-page-text-holder">
            <div class="col text-center">
                <a class="button" href="https://partner.tikrow.com/">
                    <p>PARTNER</p>
                </a>
            </div>
            <div class="col text-center">
                <a class="button" href="https://klient.tikrow.com/">
                    <p>KLIENT</p>
                </a>
            </div>
        </div>
        <div class="row main-info">
            <h3>Zmieniamy się dla Ciebie!</h3>
            <p>Przedstawiamy odświeżoną aplikacje Tikrow. Wybierz odpowiednią opcję logowania a w przypadku problemów skontaktuj się z naszym wsparciem poprzez infolinię <a href="tel:22-100-43-150">22 100 43 15</a> lub email: <a href="mailto: kontakt@tikrow.com"> kontakt@tikrow.com</a></p>
        </div>
    </div>
</div>
<div class="main-page-mobile">
    <div class="main-page-logo col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 text-center">
        <img src="images/logoTikrow-light.svg" class="img-fluid mainLogo" />
    </div>

    <div class="row main-page-text-holder">
        <div class="col text-center">
            <a class="button" href="https://partner.tikrow.com/">
                <p>PARTNER</p>
            </a>
        </div>
        <div class="col text-center">
            <a class="button" href="https://klient.tikrow.com/">
                <p>KLIENT</p>
            </a>
        </div>
    </div>
    <div class="row main-info">
        <h3>Zmieniamy się dla Ciebie!</h3>
        <p>Przedstawiamy odświeżoną aplikacje Tikrow. Wybierz odpowiednią opcję logowania a w przypadku problemów skontaktuj się z naszym wsparciem poprzez infolinię <a href="tel:22-100-43-150">22 100 43 15</a> lub email: <a href="mailto: kontakt@tikrow.com"> kontakt@tikrow.com</a></p>
    </div>
</div>
</div>
</body>
</html>