<style>
    #not-allowed {
        display: flex;
        width: 100%;
        color: #002539;
        font-size: 3rem;
        text-align: center;
        height: 100%;
        flex-wrap: wrap;
        justify-content: center;
        align-content: center;
    }
</style>

<div id="not-allowed">
    <p>
        <?=$this->fontAwesome('ban', ['class' => 'fa-4x']) ?>
        <br>
        Brak dostępu spoza sieci Tikrow.
    </p>
</div>