<?= $this->form($this->form, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL) ?>

<?php
$autocompleteValues = $this->json($this->autocomplete_values ?? []);
$autocompletePayer = $this->json($this->autocomplete2 ?? []);
$this->inlineScript()->captureStart();

echo <<<JS
    $(function() {
        var autocompleteData = {$autocompleteValues};
        var autocompPayer = {$autocompletePayer}
        new AutocompleteSingle('city', '{$this->url('autocomplete/dictionary', ['dictionary' => \Hr\Entity\Dictionary::DIC_CITIES])}', autocompleteData);
        new AutocompleteSingle('payer','{$this->url('autocomplete/payer')}', autocompPayer);
        new Autocomplete('customerGroups');
        
        new ComplexDictionary('format');
        new ComplexDictionary('size');
        new ComplexDictionary('chain');
        
        Utils.initExtendDictionaryButtons();
        Utils.initExtendPayerButtons();
    });
JS;
$this->inlineScript()->captureEnd();
?>