<div class="form-group">
    <label>Nazwa</label>
    <select name="customer" id="customer">
        <option value=""></option>
    </select>
</div>

<?= $this->formSl($this->form, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL, 1) ?>

<style>
    div.checkbox {
        display: none;
    }
</style>

<?php
$autocompleteValues = $this->json($this->autocomplete_values ?? []);
$this->inlineScript()->captureStart();
echo <<<JS
    $(function() {
        const autocompleteData = {$autocompleteValues};
        new AutocompleteSingle('customer','{$this->url('autocomplete/customer')}', autocompleteData, null, true);
        
        $("#customer").on('select2:select', function(e) {
            $("#name").val(e.params.data.id);
        })
    });
JS;
$this->inlineScript()->captureEnd();
?>
