<?php

namespace Notifications\Repository;

/**
 * EmailThresholdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailThresholdRepository extends \Doctrine\ORM\EntityRepository
{
}
