<?php

namespace Notifications\Repository;

/**
 * EmailMessageContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailMessageContentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEmailTemplate(string $type)
    {
        $qb = $this->createQueryBuilder('c');
//        $qb->select('c.subject', 'c.content', 'e.address');
        $qb->join('c.message', 'm');
        $qb->leftJoin('m.emailAddressJoints', 'j');
        $qb->leftJoin('j.emailAddress', 'e');
        $qb->andWhere('m.key = :key')->setParameter('key', $type);
        $template = $qb->getQuery()->execute();

        if (empty($template)) {
            throw new \Exception("Email template of type `$type` doesn't exist.");
        }

        $template = $template[0];

        $data = [
            'subject' => $template->getSubject(),
            'content' => $template->getContent(),
            'emails' => [],
        ];

        foreach ($template->getMessage()->getEmailAddressJoints() as $joint) {
            $data['emails'][] = $joint->getEmailAddress()->getAddress();
        }

        return $data;
    }
}
