<?php

namespace Customers\Repository;

/**
 * CustomerTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerTemplateRepository extends \Doctrine\ORM\EntityRepository
{
}
