<div class="history-back">
    <i class="fa fa-arrow-circle-o-left fa-x3" aria-hidden="true"></i>
</div>

<div class="text-center">
    <div class="row">
        <div class="col-md-12 col-xs-12">
            <ul style="list-style: none">
                <?php foreach ($this->monitoringGroups as $categoryId => $m): ?>
                    <?php
                    if ($m['enabled']) {
                        $class = $m['fulfilled'] ? 'monitoring-filled' : 'monitoring-new';
                        $href = $this->url('fulfilments/user/monitorings', [
                            'id' => $this->urlParam('id'),
                            'category-id' => $categoryId
                        ]);
                    } else {
                        $class = 'monitoring-disabled';
                        $href = '#';
                    }
                    ?>

                    <li class="monitoring <?= $class ?>">
                        <a class="monitoring-href text-center" href="<?= $href ?>">
                            <?= $m['name'] ?>
                        </a>
                    </li>
                <?php endforeach; ?>
                <?php foreach ($this->userMenu as $key => $menu) : ?>
                    <li class="monitoring monitoring-new">
                        <a class="monitoring-href text-center"
                           href="<?= $this->url($menu['route'], ['id' => $this->urlParam('id'), 'userId' => $this->urlParam('id')]) ?>">
                            <?= $menu['label'] ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>