<div class="alert alert-info" role="alert">
    <?=$this->translate('Akceptowane formaty importu danych to: <b>CSV</b>, <b>XLS</b>, <b>XLSX</b>') ?>.
</div>

<div>
    <input id="customersUpload" type="file" name="customersUpload" />
</div>

<script>
    const filetypes = FileUpload.TYPE_CSV + "|" + FileUpload.TYPE_XLS + "|" + FileUpload.TYPE_XLSX;

    new FileUpload(
        'customersUpload',
        '<?=$this->url('customers/import', ['action' => 'upload']) ?>',
        filetypes,
        false,
        null,
        function() {
            window.location = location;
        }
    );
</script>