<div class="row">
    <div class="col-md-12">
        <?= $this->operations([
            [
                'icon' => 'plus',
                'label' => 'dodaj',
                'class' => 'a-add',
                'route' => 'settings/dictionaries-old/add',
                'params' => ['id' => $this->urlParam('id')]
            ],
        ]) ?>
    </div>
    <div class="col-md-12">
        <table class="table table-condensed table-striped">
            <thead>
            <tr>
                <th><?= $this->translate('Wartość') ?></th>
                <th><?= $this->translate('Aktywne') ?></th>
                <th><?= $this->translate('Powiązane') ?></th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            <?php if (empty($this->details)): ?>
                <tr>
                    <td colspan="4" class="text-center"><?= $this->translate('Brak wartości') ?></td>
                </tr>
            <?php endif; ?>

            <?php foreach ($this->details as $detail): ?>
                <tr>
                    <td><?= $detail->getName() ?></td>
                    <td><?= $this->chk($detail->getIsActive()) ?></td>
                    <td>
                        <a href="<?= $this->url('settings/dictionaries-old/connected', ['id' => $detail->getId()]) ?>"
                           title="<?= $this->translate('Pokaż wartości powiązane') ?>">
                            <?= $detail->getChildren()->count() ?>
                            <?= $this->fontAwesome('caret-square-o-right') ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?= $this->url('settings/dictionaries-old/edit', ['id' => $detail->getId()]) ?>"
                           title="<?= $this->translate('Edytuj') ?>"
                           class="a-edit"><?= $this->fontAwesome('pencil') ?></a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<?php
/*
$this->headScript()->appendFile('/js/min/dictionaries.js', 'text/javascript');
$this->inlineScript()->captureStart();

echo <<<JS
    $(function() {
        const dic = new Dictionaries();
        dic.urlList = '{$this->url('settings/dictionaries-old/details', ['id' => $this->urlParam('id')])}';
        dic.initEvents();
        
        connectImportButton('#dictionariesOldUpload')
    });
JS;

$this->inlineScript()->captureEnd();
*/
?>