<div class="row">
    <div class="col-md-12">
        <table class="table table-condensed table-striped">
            <thead>
                <tr>
                    <th><?=$this->translate('Nazwa') ?></th>
                    <th><?=$this->translate('Klucz') ?></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($this->dictionaries as $dictionary): ?>
                    <tr>
                        <td>
                            <?=$dictionary->getName() ?>

                            <?php if ($parent = $dictionary->getParent()): ?>
                                <small class="text-muted" title="<?=$this->translate('Słownik nadrzędny') ?>">[<?=$parent->getName() ?>]</small>
                            <?php endif; ?>
                        </td>
                        <td><?=$dictionary->getKey() ?></td>
                        <td>
                            <a href="<?=$this->url('settings/dictionaries-old/details', ['id' => $dictionary->getId()]) ?>" title="<?=$this->translate('Szczegóły') ?>"><?=$this->fontAwesome('table') ?></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>