<div class="row">
    <div class="col-md-1 text-center">
        <?=$this->fontAwesome('frown-o', ['class' => 'fa-5x', 'style' => 'color: #00304a']) ?>
    </div>
    <div class="col-md-11 visible-md-block visible-lg-block">
        <h1><?=$this->translate('Wystąpił błąd') ?></h1>
        <p>
            <?=$this->translate('Prosimy o odświeżenie strony albo kontakt z administratorem serwisu.') ?>
        </p>
    </div>
    <div class="col-md-12 visible-sm-block visible-xs-block text-center">
        <h1><?=$this->translate('Wystąpił błąd') ?></h1>
        <p>
            <?=$this->translate('Prosimy o odświeżenie strony albo kontakt z administratorem serwisu.') ?>
        </p>
    </div>
</div>

<?php if (! empty($this->display_exceptions)) : ?>
<h2><?= $this->message ?></h2>
    <?php if (isset($this->exception)
        && ($this->exception instanceof \Exception || $this->exception instanceof \Error)) : ?>
<hr/>

<h2>Additional information:</h2>
<h3><?= get_class($this->exception) ?></h3>
<dl>
    <dt>File:</dt>
    <dd>
        <pre><?= $this->exception->getFile() ?>:<?= $this->exception->getLine() ?></pre>
    </dd>
    <dt>Message:</dt>
    <dd>
        <pre><?= $this->escapeHtml($this->exception->getMessage()) ?></pre>
    </dd>
    <dt>Stack trace:</dt>
    <dd>
        <pre><?= $this->escapeHtml($this->exception->getTraceAsString()) ?></pre>
    </dd>
</dl>

        <?php if ($ex = $this->exception->getPrevious()) : ?>
<hr/>

<h2>Previous exceptions:</h2>
<ul class="list-unstyled">
            <?php $icount = 0 ?>
            <?php while ($ex) : ?>
    <li>
        <h3><?= get_class($ex) ?></h3>
        <dl>
            <dt>File:</dt>
            <dd>
                <pre><?= $ex->getFile() ?>:<?= $ex->getLine() ?></pre>
            </dd>
            <dt>Message:</dt>
            <dd>
                <pre><?= $this->escapeHtml($ex->getMessage()) ?></pre>
            </dd>
            <dt>Stack trace:</dt>
            <dd>
                <pre><?= $this->escapeHtml($ex->getTraceAsString()) ?></pre>
            </dd>
        </dl>
    </li>
                <?php
                $ex = $ex->getPrevious();
                if (++$icount >= 50) {
                    echo '<li>There may be more exceptions, but we do not have enough memory to process it.</li>';
                    break;
                }
                ?>
            <?php endwhile ?>
</ul>
        <?php endif ?>
    <?php else : ?>
        <h3>No Exception available</h3>
    <?php endif ?>
<?php endif ?>
