<?php
$form = new \Laminas\Form\Form();
$form->setAttribute('action', '/users/data/' . $this->userId);
$form->setAttribute('method', 'POST');
$form->setAttribute('id', 'editForm');

$actualDataArray = [];
foreach ($this->actualData as $index) {
    $actualDataArray[$index->getData()->getId()] = $index->getValue();
}

$oldDataArray = [];
foreach ($this->oldData as $index => $r) {
    foreach ($r->getDetails() as $detail) {
        $oldDataArray[$index][$detail->getData()->getId()] = $detail->getValue();
    }
}
?>

<?= $this->partial('users/tabs') ?>

<?php if ($this->blocked): ?>
    <div class="alert alert-danger"><?= $this->translate('Użytkownik zablokowany') ?></div>
<?php endif; ?>

<?php if ($this->futureCommissions): ?>
    <div class="alert alert-warning"><?= $this->translate('Użytkownik posiada przyjęte zlecenia') ?></div>
<?php endif; ?>

<?= $this->form()->openTag($form) ?>
<?php if (!empty($this->userData)) : ?>
    <?php
    $statuses = \Users\Entity\UserDataVersion::getDataStatus();
    if ($this->futureCommissions) {
        unset($statuses[\Users\Entity\UserDataVersion::STATUS_REJECTED]);
        unset($statuses[\Users\Entity\UserDataVersion::STATUS_PROCESSED]);
    }

    $selectElement = new \Laminas\Form\Element\Select();
    $selectElement->setValueOptions($statuses);
    $selectElement->setEmptyOption('Wybierz ...');
    $selectElement->setLabel('Zmień status aktualnych danych');
    $selectElement->setName('accept-last-data');

    $notifications = [];
    foreach ($this->notifications as $notification) {
        $notifications[$notification->getId()] = $notification->getSubject();
    }

    $selectNotifications = new \Laminas\Form\Element\Select();
    $selectNotifications->setValueOptions($notifications);
    $selectNotifications->setEmptyOption('Wybierz ...');
    $selectNotifications->setLabel('Wiadomość dla partnera');
    $selectNotifications->setName('notification');

    $remarks = new \Laminas\Form\Element\Text('comment');
    $remarks->setLabel('Uwagi');
    ?>

    <div class="col-md-10">
        <div class="row">
            <div class="col-md-3 mr-5">
                <?= $this->formRow($selectElement) ?>
            </div>
            <div class="col-md-4 mr-5">
                <?= $this->formRow($selectNotifications) ?>
            </div>
            <div class="col-md-4">
                <?= $this->formRow($remarks) ?>
            </div>
        </div>

        <?php
        $submit = new \Laminas\Form\Element\Submit('Zapisz', [
            'label' => 'Zapisz',
        ]);
        $submit->setAttribute('class', 'btn btn-sl');

        $saveWithoutStatus = new \Laminas\Form\Element\Submit('save-without-status', [
            'label' => 'Zapisz bez statusu',
        ]);
        $saveWithoutStatus->setAttribute('class', 'btn btn-primary');

        $back = new \Laminas\Form\Element\Button('Cofnij', [
            'label' => 'Cofnij',
        ]);
        $back->setAttribute('class', 'btn btn-default go-back');
        ?>

        <div class="form-group">
            <?= $this->form_element($submit) ?>
            <?= $this->form_element($saveWithoutStatus) ?>
            <?= $this->form_element($back) ?>
        </div>
    </div>

    <div class="col-md-2 text-right">
        <a
                href="<?= $this->url('messages/default', ['action' => 'individual', 'id' => $this->urlParam('id')]) ?>"
                class="btn btn-sl"
                id="a-messages"
        ><?= $this->translate('Wiadomości') ?></a>
    </div>

    <table id="userDataTable" class="table table-condensed table-hover ">
        <thead>
        <tr>
            <th><?= $this->translate('Id') ?></th>
            <th><?= $this->translate('Klucz') ?></th>
            <th><?= $this->translate('Nazwa') ?></th>
            <th>
                <?= $this->translate('Wersja: ') ?>
                <?= isset($this->actualData[0]) ? $this->actualData[0]->getVersion()->getId() : '' ?><br/>
                <?= $this->translate('Data: ') ?>
                <?= isset($this->actualData[0]) ? $this->actualData[0]->getVersion()->getCreationDate()->format('Y-m-d H:i:s') : '' ?>
                <br/>
                <?= $this->translate('Utworzył: ') ?>
                <?= isset($this->actualData[0]) ? $this->actualData[0]->getVersion()->getCreatingUser()->getFullName() : '' ?>
                <br/>
                <?= $this->translate('Status: ') ?>
                <?= isset($this->actualData[0]) ? \Users\Entity\UserDataVersion::getDataStatus()[$this->actualData[0]->getVersion()->getStatus()] : '' ?>
                <br/>
                <?= $this->translate('Zmienił: ') ?>
                <?= (isset($this->actualData[0]) && $this->actualData[0]->getVersion()->getStatusChangeUser()) ? $this->actualData[0]->getVersion()->getStatusChangeUser()->getFullName() : '' ?>
                <br/>
                <?= $this->translate('Data zmiany statusu:') ?>
                <?= isset($this->actualData[0]) && $this->actualData[0]->getVersion()->getStatusChangeDate() ? $this->actualData[0]->getVersion()->getStatusChangeDate()->format('Y-m-d H:i:s') : '' ?>
            </th>
            <?php if (count($this->oldData) >= 1) : ?>
                <th>
                    <?= $this->translate('Wersja: ') ?>
                    <?= isset($this->oldData[0]) ? $this->oldData[0]->getId() : '' ?><br/>
                    <?= $this->translate('Data: ') ?>
                    <?= isset($this->oldData[0]) ? $this->oldData[0]->getCreationDate()->format('Y-m-d H:i:s') : '' ?>
                    <br/>
                    <?= $this->translate('Utworzył') ?>
                    <?= isset($this->oldData[0]) ? $this->oldData[0]->getCreatingUser()->getFullName() : '' ?><br/>
                    <?= $this->translate('Status: ') ?>
                    <?= isset($this->oldData[0]) ? \Users\Entity\UserDataVersion::getDataStatus()[$this->oldData[0]->getStatus()] : '' ?>
                    <br/>
                    <?= $this->translate('Zmienił: ') ?>
                    <?= (isset($this->oldData[0]) && $this->oldData[0]->getStatusChangeUser()) ? $this->oldData[0]->getStatusChangeUser()->getFullName() : '' ?>
                    <br/>
                    <?= $this->translate('Data zmiany statusu:') ?>
                    <?= isset($this->oldData[0]) && $this->oldData[0]->getStatusChangeDate() ? $this->oldData[0]->getStatusChangeDate()->format('Y-m-d H:i:s') : '' ?>
                </th>
            <?php endif; ?>
            <?php if (count($this->oldData) > 1) : ?>
                <th>
                    <?= $this->translate('Wersja: ') ?>
                    <?= isset($this->oldData[1]) ? $this->oldData[1]->getId() : '' ?><br/>
                    <?= $this->translate('Data: ') ?>
                    <?= isset($this->oldData[1]) ? $this->oldData[1]->getCreationDate()->format('Y-m-d H:i:s') : '' ?>
                    <br/>
                    <?= $this->translate('Utworzył: ') ?>
                    <?= isset($this->oldData[1]) ? $this->oldData[1]->getCreatingUser()->getFullName() : '' ?><br/>
                    <?= $this->translate('Status: ') ?>
                    <?= isset($this->oldData[1]) ? \Users\Entity\UserDataVersion::getDataStatus()[$this->oldData[1]->getStatus()] : '' ?>
                    <br/>
                    <?= $this->translate('Zmienił: ') ?>
                    <?= (isset($this->oldData[1]) && $this->oldData[1]->getStatusChangeUser()) ? $this->oldData[1]->getStatusChangeUser()->getFullName() : '' ?>
                    <br/>
                    <?= $this->translate('Data zmiany statusu:') ?>
                    <?= isset($this->oldData[1]) && $this->oldData[1]->getStatusChangeDate() ? $this->oldData[1]->getStatusChangeDate()->format('Y-m-d H:i:s') : '' ?>
                </th>
            <?php endif; ?>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->userData as $data) : ?>
            <tr>
                <td><?= $data->getId() ?></td>
                <td><?= $data->getKey() ?></td>
                <td><?= $data->getName() ?></td>

                <?php if ($data->getType() == \Users\Entity\UserData::TYPE_FILE): ?>
                    <td>
                        <?php
                        $info = null;
                        $path = $this->fileService->getPath(\Hr\File\FileService::TYPE_QUESTIONNAIRE_ATTACHMENTS, ['USER_ID' => $this->userId]);
                        $file = $this->objectManager->getRepository(\Users\Entity\UserDataDetail::class)->getActiveValueForKey($userId, $data->getKey());
                        if ($file) {
                            $filePath = $path . '/' . $file[0]->getValue();

                        }
                        if (isset($actualDataArray[$data->getId()]) && $file && file_exists($filePath)):
                            $info = getimagesize($filePath);
                            ?>
                            <?php if (is_array($info)) : ?>
                            <a
                                    href="<?= $this->url('users/data/download', ['id' => $this->urlParam('id'), 'field' => $data->getKey()]) ?>"
                                    class="show-modal"
                            ><?= $this->translate('pobierz') ?></a>
                            <input
                                    type="hidden"
                                    name="userData[<?= $data->getId() ?>]"
                                    value="<?= $actualDataArray[$data->getId()] ?>"
                            />
                            <input
                                    type="hidden"
                                    name="userOldData[<?= $data->getId() ?>]"
                                    value="<?= $actualDataArray[$data->getId()] ?>"
                            />
                        <?php else : ?>
                            <a href="<?= $this->url('users/data/download', ['id' => $this->urlParam('id'), 'field' => $data->getKey()]) ?>"><?= $this->translate('pobierz') ?></a>
                            <input
                                    type="hidden"
                                    name="userData[<?= $data->getId() ?>]"
                                    value="<?= $actualDataArray[$data->getId()] ?>"
                            />
                            <input
                                    type="hidden"
                                    name="userOldData[<?= $data->getId() ?>]"
                                    value="<?= $actualDataArray[$data->getId()] ?>"
                            />
                        <?php endif ?>
                        <?php else: ?>
                            -
                        <?php endif; ?>
                    </td>

                    <?php foreach ($oldDataArray as $index => $od) : ?>
                        <td></td>
                    <?php endforeach; ?>
                <?php else: ?>
                    <?php
                    if ($data->getType() == \Users\Entity\UserData::TYPE_SIMPLE_ARRAY) {
                        $valueOptions = call_user_func($data->getParams());
                        $elem = new \Laminas\Form\Element\Select(
                            "userData[{$data->getId()}]",
                            ['value_options' => $valueOptions, 'empty_option' => '-']
                        );
                    } elseif ($data->getType() == \Users\Entity\UserData::TYPE_SELECT_OBJECT) {
                        $params = $data->getParams();

                        if (strstr($params, '::')) {
                            // class with method provided
                            [$entity, $method] = explode('::', $params);
                        } else {
                            // only method
                            $entity = $params;
                            $method = 'findBy';
                        }

                        $elem = new \DoctrineModule\Form\Element\ObjectSelect(
                            "userData[{$data->getId()}]",
                            [
                                'empty_option' => 'wybierz',
                                'object_manager' => $this->objectManager,
                                'target_class' => $entity,
                                'property' => 'name',
                                'find_method' => [
                                    'name' => $method,
                                    'params' => [
                                        'criteria' => ['isActive' => true],
                                    ],
                                ],
                            ]
                        );
                    } else {
                        $elem = new \Laminas\Form\Element\Text(
                            "userData[{$data->getId()}]"
                        );
                        $valueOptions = null;
                    }

                    (!$data->getIsActive()) ? $elem->setAttribute('readonly', 'readonly') : '';

                    $hidden = new \Laminas\Form\Element\Hidden(
                        "userOldData[{$data->getId()}]"
                    );
                    if (isset($actualDataArray[$data->getId()])) {
                        $elem->setValue($actualDataArray[$data->getId()]);
                        $hidden->setValue($actualDataArray[$data->getId()]);
                    }
                    ?>

                    <td>
                        <?= $this->formElement($elem) ?>
                        <?= $this->formElement($hidden) ?>
                    </td>

                    <?php foreach ($oldDataArray as $index => $od) : ?>
                        <td>
                            <?php if (isset($od[$data->getId()])): ?>
                                <?php if (isset($valueOptions)): ?>
                                    <?= $valueOptions[$od[$data->getId()]] ?? '-' ?>
                                <?php else: ?>
                                    <?= $od[$data->getId()] ?>
                                <?php endif; ?>
                            <?php else: ?>
                                -
                            <?php endif; ?>
                        </td>
                    <?php endforeach; ?>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>


<?php endif; ?>
<?= $this->form()->closeTag($form) ?>
<?php
$this->headScript()->appendFile($this->basePath('js/min/user.js'));
$this->inlineScript()->captureStart();
echo <<<JS
    $(function() {
        const user = new User;
        
        user.initUserDataEvents();
    });
JS;
$this->inlineScript()->captureEnd();
?>
