<div class="history-back">
    <i class="fa fa-arrow-circle-o-left fa-x3" aria-hidden="true"></i>
</div>

<div class="text-center">
    <?php
    $this->placeholder('addressBar')
        ->set($this->addressBar($this->urlParam('id')))
        ->setPrefix('<div class="addresbar text-center">')
        ->setPostfix('</div>')
    ?>
    <div class="row">
        <div class="col-md-12 col-xs-12">
            <ul style="list-style: none">
                <?php foreach ($this->monitoringGroups as $categoryId => $m): ?>
                    <?php
                    if ($m['enabled']) {
                        $class = $m['fulfilled'] ? 'monitoring-filled' : 'monitoring-new';
                        $href = $this->url('fulfilments/customer/monitorings', [
                            'id' => $this->urlParam('id'),
                            'category-id' => $categoryId,
                        ]);
                    } else {
                        $class = 'monitoring-disabled';
                        $href = '#';
                    }
                    ?>

                    <li class="monitoring <?= $class ?>">
                        <a class="monitoring-href text-center" href="<?= $href ?>">
                            <?= $m['name'] ?>
                        </a>
                    </li>
                <?php endforeach; ?>
                <?php foreach ($this->customerMenu as $key => $menu) : ?>
                    <li class="monitoring monitoring-new">
                        <a
                                class="monitoring-href text-center"
                                href="<?= $this->url($menu['route'], ['id' => $this->urlParam('id'), 'customerId' => $this->urlParam('id')]) ?>"
                        >
                            <?= $menu['label'] ?>
                        </a>
                    </li>
                <?php endforeach; ?>

                <?php if ($this->isAllowed(\Hr\Acl\AclService::CUSTOMER_DETAILS_ORDER)): ?>
                    <li class="monitoring monitoring-new">
                        <a
                                class="monitoring-href text-center"
                                href="<?= $this->url('orders/new', ['id' => $this->urlParam('id')]) ?>"
                        ><?= $this->translate('Nowe zamówienie ') ?></a>
                    </li>
                <?php endif; ?>
            </ul>
        </div>
    </div>