<?php

use Customers\Controller\SaveController;
use Customers\Controller\UsersController;
use Laminas\Navigation\Navigation;

$action = $this->urlParam('action');
$controller = $this->urlParam('controller');
$type = $this->urlParam('type');

echo $this->navigation()->menu()->renderMenu(
    new Navigation(
        [
            [
                'label' => $this->translate('Edycja'),
                'uri' => $this->url('customers/edit', ['id' => $this->urlParam('id')]),
                'active' => $controller == SaveController::class,
            ],
            [
                'label' => $this->translate('Relacje'),
                'uri' => $this->url('customers/users', ['id' => $this->urlParam('id')]),
                'active' => $controller == UsersController::class,
            ],
        ]
    ),
    [
        'tabs' => true,
        'page' => true,
        'ulClass' => 'mb-2',
    ]
);