<?= $this->partial('users/index/tabs') ?>

<table class="table">
    <thead>
        <tr>
            <th><?=$this->translate('Data utworzenia') ?></th>
            <th><?=$this->translate('Data wygaśnięcia') ?></th>
            <th><?=$this->translate('Zgłaszający') ?></th>
            <th><?=$this->translate('Partner') ?></th>
            <th><?=$this->translate('Powód') ?></th>
            <th><?=$this->translate('Data zatwierdzenia') ?></th>
            <th><?=$this->translate('Zatwierdził') ?></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php
            /** @var \Users\Entity\RemoteLogin $login */
            foreach ($this->waiting as $login):
        ?>
            <tr>
                <td><?=$this->dt($login->getCreationDate()) ?></td>
                <td><?=$this->dt($login->getExpirationDate()) ?></td>
                <td><?=$login->getCreatingUser()->getFullName() ?></td>
                <td>
                    <?=$login->getPartner()->getFullName() ?>
                    <small class="text-muted">[<?=$login->getPartner()->getId() ?>]</small>
                </td>
                <td><?=$login->getReason() ?></td>
                <td><?=$login->getConfirmationDate()  ? $this->dt($login->getConfirmationDate()) : '-' ?></td>
                <td><?=$login->getConfirmingUser() ? $login->getConfirmingUser()->getFullName() : '-' ?></td>
                <td>
                    <?php if ($login->canConfirm($this->identity()['id'])): ?>
                        <a href="<?=$this->url('users/login', ['action' => 'confirm', 'id' => $login->getId()]) ?>" class="btn btn-sm btn-success a-confirm"><?=$this->translate('Potwierdź') ?></a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php
$this->headScript()->appendFile($this->basePath('js/min/user.js'));
$this->inlineScript()->captureStart();
echo <<<JS
    $(function() {
        const user = new User();
        user.initEvents();
    });
JS;
$this->inlineScript()->captureEnd();
?>