<?php

namespace Configuration\Repository;

/**
 * ObjectFieldDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectFieldDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
