<?php

namespace Configuration\Repository;

/**
 * ResourcePositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourcePositionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPermissionsWithResourceNames(int $positionId)
    {
        $qb = $this->createQueryBuilder('rp');
        $qb->select('rp', 'r');
        $qb->innerJoin('rp.resource', 'r');
        $qb->andWhere($qb->expr()->eq('rp.position', $positionId));

        return $qb->getQuery()->execute();
    }
}
