<div class="row">
    <div class="col-md-12">
        <?=$this->operations([
            [
                'icon' => 'plus',
                'label' => 'dodaj',
                'class' => 'a-add',
                'route' => 'settings/monitoring-categories/add',
            ],
        ]) ?>
    </div>
    <div class="col-md-12">
        <table class="table table-condensed table-striped">
            <thead>
                <tr>
                    <th><?=$this->translate('Nazwa') ?></th>
                    <th><?=$this->translate('Kolejność') ?></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php if (empty($this->categories)): ?>
                    <tr><td colspan="3" class="text-center"><?=$this->translate('Brak wartości') ?></td></tr>
                <?php endif; ?>

                <?php foreach($this->categories as $category): ?>
                    <tr>
                        <td><?=$category->getName() ?></td>
                        <td><?=$category->getSequence() ?></td>
                        <td>
                            <a href="<?=$this->url('settings/monitoring-categories/edit', ['id' => $category->getId()]) ?>" title="<?=$this->translate('Edytuj') ?>" class="a-edit"><?=$this->fontAwesome('pencil') ?></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>