<div class="row">
    <div class="col-md-12">
        <?= $this->operations([
            [
                'icon' => 'plus',
                'label' => 'dodaj',
                'route' => 'document-templates/add',
                'resource' => 'documentTemplates',
                'mode' => 'add',
            ],
        ]) ?>
    </div>
</div>

<?= $this->searchForm($this->search) ?>

<?= $this->table($this->table, 'document-templates') ?>

<?php
$this->inlineScript()->captureStart();

echo <<<JS
    $(function() {
        Utils.setActivateEvents();
    });
JS;
$this->inlineScript()->captureEnd();
?>
