<style>
    h3, h4, h5 {
        margin: 1rem 0;
    }
</style>
<?= $this->html ?>

<?php
$this->inlineScript()->captureStart();
echo <<<JS
    $(function() {
        $(".btn-execute").click(async (e) => {
            const payload = $(e.currentTarget).data('payload')     
            await $.post('/cron/execute', payload)
            new NotifySuccess('Polecenie zostało wykonane')
        })
    });
JS;
$this->inlineScript()->captureEnd();
?>