Settings\Entity\NotificationHour:
  type: entity
  table: settingsNotificationHours
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    day:
      type: integer
      nullable: false
    from:
      type: time
      nullable: false
      column: '`from`'
    to:
      type: time
      nullable: false
      column: '`to`'