<?php

use AssemblyOrders\Controller\RankingController;
use AssemblyOrders\Controller\SaveController;
use Laminas\Navigation\Navigation;

$action = $this->urlParam('action');
$controller = $this->urlParam('controller');
$type = $this->urlParam('type');

echo $this->navigation()->menu()->renderMenu(
    new Navigation(
        [
            [
                'label' => $this->translate('Edycja'),
                'uri' => $this->url('assembly-orders/edit', ['id' => $this->urlParam('id')]),
                'active' => $controller == SaveController::class,
            ],
            [
                'label' => $this->translate('Ranking'),
                'uri' => $this->url('assembly-orders/rankings', ['id' => $this->urlParam('id')]),
                'active' => $controller == RankingController::class,
            ],
        ]
    ),
    [
        'tabs' => true,
        'page' => true,
        'ulClass' => 'mb-2',
    ]
);