<a href="<?= $this->url('notifications/cycles', ['action' => 'add']) ?>" class="btn btn-primary">dodaj</a>

<table class="table">
    <thead>
    <tr>
        <th rowspan="2"><?= $this->translate('Cykl komunikacji') ?></th>
        <th colspan="2" class="text-center"><?= $this->translate('Czasy w minutach') ?></th>
        <th colspan="2" class="text-center"><?= $this->translate('Ranking') ?></th>
        <th rowspan="2"></th>
    </tr>
    <tr>
        <th><?= $this->translate('opóźnienie') ?></th>
        <th><?= $this->translate('wyświetlanie') ?></th>
        <th><?= $this->translate('od') ?></th>
        <th><?= $this->translate('do') ?></th>
    </tr>
    </thead>
    <tbody>
    <?php /** @var \Notifications\Entity\Cycle $cycle */
    foreach ($this->cycles as $i => $cycle): ?>
        <tr>
            <td><?= $i + 1 ?></td>
            <td><?= $cycle->getDelay() ?></td>
            <td><?= $cycle->getDisplay() ?></td>
            <td><?= $cycle->getRankingFrom() ?></td>
            <td><?= $cycle->getRankingTo() ?></td>
            <td>
                <a href="<?= $this->url('notifications/cycles', ['action' => 'edit', 'id' => $cycle->getId()]) ?>"><?= $this->fontAwesome('pencil') ?></a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>