<?php use Laminas\View\Renderer\PhpRenderer; ?>
<?php /** @var PhpRenderer $this */ ?>
<div class="row">
    <div class="col-md-12">
        <?= $this->operations([
            [
                'icon' => 'plus',
                'label' => 'dodaj',
                'route' => 'configuration/holidayDates/add',
                'params' => [
                    'action' => 'add',
                ],
            ],
        ]) ?>
    </div>
</div>
<?= $this->table($this->table ?? null, 'holidayDates') ?>
<script>
    $(function () {
        $('body').on('click', '.a-holiday-date-remove', function (e) {
            e.preventDefault();

            let href = $(e.currentTarget).attr('href');

            bootbox.confirm("Czy na pewno chcesz usunąć rekord?", (resp) => {
                if (resp) {
                    $.post(href, (resp) => {
                        if (resp === 'ok') {
                            window.location.reload();
                        }
                    })
                }
            })
            return false;
        });
    });
</script>