<div class="row">
    <div class="col-md-12">
        <?=$this->operations([
            [
                'icon' => 'plus',
                'label' => 'dodaj',
                'route' => 'settings/subchains/add',
            ],
        ]) ?>
    </div>
</div>
<?= $this->searchForm($this->search) ?>

<?=$this->table($this->table, 'settings/subchains') ?>
<?php

$this->inlineScript()->captureStart();

echo <<<JS
    $(function() {
        new Autocomplete('chain');
    });
JS;
$this->inlineScript()->captureEnd();
?>