<div class="row">
    <?php foreach($this->macroregions as $macroregion): ?>
        <div class="col-md-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title"><?=$macroregion->getName() ?></h3>
                </div>
                <div class="panel-body">
                    <!-- subregion box -->
                    <?php if(isset($this->subregions[$macroregion->getId()])): ?>
                        <div class="row">
                            <?php $i = 1; ?>
                            <?php foreach($this->subregions[$macroregion->getId()] as $subregion): ?>
                                <div class="col-md-6">
                                    <div class="panel panel-info">
                                        <div class="panel-heading">
                                            <h3 class="panel-title">
                                                <?=$subregion->getName() ?>

                                                <div class="dropdown pull-right">
                                                    <button class="btn btn-default btn-xs dropdown-toggle" type="button" id="dropdownMenuSub<?=$subregion->getId() ?>" data-toggle="dropdown">
                                                        <?=$this->fontAwesome('cog') ?>
                                                        <span class="caret"></span>
                                                    </button>

                                                    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenuSub<?=$subregion->getId() ?>">
                                                        <li role="presentation">
                                                            <a role="menuitem" tabindex="-1" class="a-assign" data-id="<?=$subregion->getId() ?>" href="<?=$this->url('settings/regions', ['action' => 'assign-subregion']) ?>"><?=$this->translate('Przypisz do innego makroregionu') ?></a>
                                                        </li>
                                                        <li role="presentation">
                                                            <a role="menuitem" tabindex="-1" class="a-unassign" data-id="<?=$subregion->getId() ?>" href="<?=$this->url('settings/regions', ['action' => 'unassign-subregion']) ?>"><?=$this->translate('Usuń przypisanie do makroregionu') ?></a>
                                                        </li>
                                                    </ul>

                                                </div>
                                                <div class="clearfix"></div>
                                            </h3>
                                        </div>
                                        <div class="panel-body">
                                            <!-- regions list -->
                                            <?php if(isset($this->regions[$subregion->getId()])): ?>
                                                <?php foreach($this->regions[$subregion->getId()] as $region): ?>


                                                    <div class="dropdown pull-left mr-5 mb-5">
                                                        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu<?=$region->getId() ?>" data-toggle="dropdown">
                                                            <?=$region->getName() ?>

                                                            <?php if($region->getKey()): ?>
                                                                <small class="text-muted"><?=$region->getKey() ?></small>
                                                            <?php endif; ?>

                                                            <span class="caret"></span>
                                                        </button>
                                                        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu<?=$region->getId() ?>">
                                                            <li role="presentation">
                                                                <a role="menuitem" tabindex="-1" class="a-assign" data-id="<?=$region->getId() ?>" href="<?=$this->url('settings/regions', ['action' => 'assign-region']) ?>"><?=$this->translate('Przypisz do innego subregionu') ?></a>
                                                            </li>
                                                            <li role="presentation">
                                                                <a role="menuitem" tabindex="-1" class="a-unassign" data-id="<?=$region->getId() ?>" href="<?=$this->url('settings/regions', ['action' => 'unassign-region']) ?>"><?=$this->translate('Usuń przypisanie do subregionu') ?></a>
                                                            </li>
                                                        </ul>
                                                    </div>
                                                <?php endforeach; ?>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>

                                <?php if($i++ % 2 == 0): ?>
                                    </div>
                                    <div class="row">
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h3 class="panel-title"><?=$this->translate('Nieprzypisane subregiony') ?></h3>
            </div>
            <div class="panel-body">
                
                <?php if(!empty($this->unassigned_subregions)): ?>
                    <div class="row">
                        <?php $i = 1; ?>
                        <?php foreach($this->unassigned_subregions as $subregion): ?>
                            <div class="col-md-6">
                                <div class="panel panel-info">
                                    <div class="panel-heading">
                                        <h3 class="panel-title">
                                            <?=$subregion->getName() ?>

                                            <div class="dropdown pull-right">
                                                <button class="btn btn-default btn-xs dropdown-toggle" type="button" id="dropdownMenuSub<?=$subregion->getId() ?>" data-toggle="dropdown">
                                                    <?=$this->fontAwesome('cog') ?>
                                                    <span class="caret"></span>
                                                </button>

                                                <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenuSub<?=$subregion->getId() ?>">
                                                    <li role="presentation">
                                                        <a role="menuitem" tabindex="-1" class="a-assign" data-id="<?=$subregion->getId() ?>" href="<?=$this->url('settings/regions', ['action' => 'assign-subregion']) ?>"><?=$this->translate('Przypisz do innego makroregionu') ?></a>
                                                    </li>
                                                </ul>

                                            </div>
                                            <div class="clearfix"></div>
                                        </h3>
                                    </div>
                                    <div class="panel-body">
                                        <!-- regions list -->
                                        <?php if(isset($this->regions[$subregion->getId()])): ?>
                                            <?php foreach($this->regions[$subregion->getId()] as $region): ?>
                                                <div class="dropdown pull-left mr-5 mb-5">
                                                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu<?=$region->getId() ?>" data-toggle="dropdown">
                                                        <?=$region->getName() ?>

                                                        <?php if($region->getKey()): ?>
                                                            <small class="text-muted"><?=$region->getKey() ?></small>
                                                        <?php endif; ?>

                                                        <span class="caret"></span>
                                                    </button>
                                                    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu<?=$region->getId() ?>">
                                                        <li role="presentation">
                                                            <a role="menuitem" tabindex="-1" class="a-assign" data-id="<?=$region->getId() ?>" href="<?=$this->url('settings/regions', ['action' => 'assign-region']) ?>"><?=$this->translate('Przypisz do innego subregionu') ?></a>
                                                        </li>
                                                        <li role="presentation">
                                                            <a role="menuitem" tabindex="-1" class="a-unassign" data-id="<?=$region->getId() ?>" href="<?=$this->url('settings/regions', ['action' => 'unassign-region']) ?>"><?=$this->translate('Usuń przypisanie do subregionu') ?></a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            <?php endforeach; ?>
                                        <?php endif; ?>

                                    </div>
                                </div>
                            </div>

                            <?php if($i++ % 2 == 0): ?>
                                </div>
                                <div class="row">
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
                
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h3 class="panel-title"><?=$this->translate('Nieprzypisane regiony') ?></h3>
            </div>
            <div class="panel-body">
                <!-- unassigned regions list -->
                <?php if(!empty($this->unassigned_regions)): ?>
                    <?php foreach($this->unassigned_regions as $region): ?>
                        <div class="dropdown pull-left mr-5 mb-5">
                            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu<?=$region->getId() ?>" data-toggle="dropdown">
                                <?=$region->getName() ?>

                                <?php if($region->getKey()): ?>
                                    <small class="text-muted"><?=$region->getKey() ?></small>
                                <?php endif; ?>

                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu<?=$region->getId() ?>">
                                <li role="presentation">
                                    <a role="menuitem" tabindex="-1" class="a-assign" data-id="<?=$region->getId() ?>" href="<?=$this->url('settings/regions', ['action' => 'assign-region']) ?>"><?=$this->translate('Przypisz do innego subregionu') ?></a>
                                </li>
                            </ul>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

<?php
$this->headScript()->appendFile('/js/min/regions.js', 'text/javascript');
$this->inlineScript()->captureStart();

echo <<<JS
    $(function() {
        var regions = new Regions();
        regions.initEvents();
    });
JS;

$this->inlineScript()->captureEnd();
?>