<div class="row">
    <div class="col-md-12">
        <?= $this->operations([
            [
                'icon' => 'plus',
                'label' => 'dodaj',
                'route' => 'configuration/add',
            ],
        ]) ?>
    </div>
</div>

<?= $this->searchForm($this->search) ?>
<div class="data-table">
    <table class="table table-condensed table-hover">
        <thead>
        <tr>
            <th colspan="4"></th>
            <th colspan="4" class="text-center"><?= $this->translate('Menu') ?></th>
            <th colspan="6"></th>
        </tr>
        <tr>
            <th><?= $this->translate('Nazwa / ścieżka') ?></th>
            <th><?= $this->translate('Label') ?></th>
            <th><?= $this->translate('Kolejność') ?></th>
            <th><?= $this->translate('Ikona') ?></th>
            <th><?= $this->translate('Główne') ?></th>
            <th><?= $this->translate('Klienta') ?></th>
            <th><?= $this->translate('Startowe') ?></th>
            <th><?= $this->translate('Użytkownika') ?></th>
            <th><?= $this->translate('Ukryte') ?></th>
            <th><?= $this->translate('Telefon') ?></th>
            <th><?= $this->translate('Tablet') ?></th>
            <th><?= $this->translate('PC') ?></th>
            <th><?= $this->translate('Cookie') ?></th>
            <th></th>
        </tr>
        </thead>
        <?php foreach ($this->menu as $m) : ?>
            <tr>
                <td>
                    <?= $m->getName() ?>
                    <br>
                    <small class="text-muted"><?= $m->getRoute() ?></small>
                </td>
                <td><?= $m->getLabel() ?></td>
                <td><?= $m->getSequence() ?></td>
                <td>  <?= empty($m->getIcon()) ? '' : $this->fontAwesome($m->getIcon()) ?></i></td>
                <td><?= $this->chk($m->getIsUserMenu()) ?></td>
                <td><?= $this->chk($m->getIsCustomerMenu()) ?></td>
                <td><?= $this->chk($m->getIsShortcutMenu()) ?></td>
                <td><?= $this->chk($m->getIsUserDetailsMenu()) ?></td>
                <td><?= $this->chk($m->getIsHidden()) ?></td>
                <td><?= $this->chk($m->getSettingSmall()) ?></td>
                <td><?= $this->chk($m->getSettingMedium()) ?></td>
                <td><?= $this->chk($m->getSettingLarge()) ?></td>
                <td><?= $m->getCookie() ?></td>
                <td>
                    <a href="<?= $this->url('configuration/edit', ['id' => $m->getId()]) ?>"><?= $this->fontAwesome('pencil') ?></a>
                    <a
                            href="<?= $this->url('configuration/resourcePositions', ['id' => $m->getId()]) ?>"
                            class="resource-edit-position"
                    ><?= $this->fontAwesome('user') ?></a>
                    <a
                            href="<?= $this->url('configuration/submenu', ['id' => $m->getId()]) ?>"
                            class="resource-show-submenu"
                    ><?= $this->fontAwesome('navicon') ?></a>
                </td>
            </tr>
            <tr class="config-details">
                <td colspan="16"></td>
            </tr>
        <?php endforeach ?>
    </table>
</div>
<div class="data-scroll"></div>
<?php
$this->inlineScript()->captureStart();

$this->headScript()->appendFile($this->basePath('bower_components/jquery-sortable/source/js/jquery-sortable-min.js'));
echo <<<JS
    $(function() {
        var configuration = new Configuration();
        configuration.initEvents();
    });
JS;
$this->inlineScript()->captureEnd();
?>