<table>
    <tr>
        <?php foreach ($objects as $o) : ?>
            <td>
                <?php
                switch ($o->getType()) {
                    case \Configuration\Entity\ObjectGroup::TYPE_SEARCH:
                        $class = "btn-primary";
                        break;
                    case \Configuration\Entity\ObjectGroup::TYPE_FORM:
                        $class = "btn-secondary";
                        break;
                    case \Configuration\Entity\ObjectGroup::TYPE_TABLE:
                        $class = "btn-info";
                        break;
                    default:
                        $class = "btn-warning";
                        break;
                }
                ?>
                <div class="dropup">
                    <a
                            class="btn <?= $class ?> dropdown-toggle"
                            href="#"
                            role="button"
                            data-bs-toggle="dropdown"
                            aria-expanded="false"
                    >
                        <?= $o->getName() ?> <span class="caret"></span>
                    </a>

                    <ul class="dropdown-menu">
                        <li><a
                                    href="<?= $this->url('configuration/editSequence', ['id' => $o->getId()]) ?>"
                                    class="edit-sequence dropdown-item"
                            ><?= $this->translate('Kolejność pól') ?></a></li>
                        <li><a
                                    href="<?= $this->url('configuration/editVisibility', ['id' => $o->getId()]) ?>"
                                    class="edit-privilages dropdown-item"
                            ><?= $this->translate('Uprawnienia') ?></a></li>
                    </ul>
                </div>
            </td>
        <?php endforeach; ?>
    </tr>
</table>