<div class="data-table">
    <table class="table table-condensed table-hover">
        <thead>
        <tr>
            <th><?= $this->translate('Lp.') ?></th>
            <th><?= $this->translate('Nazwa') ?></th>
            <th><?= $this->translate('Label') ?></th>
            <th><?= $this->translate('Ścieżka') ?></th>
            <th><?= $this->translate('Parametry') ?></th>
            <th><?= $this->translate('Kolejność') ?></th>
            <th><?= $this->translate('Ikona') ?></th>
            <th>
                <?= $this->translate('Menu') ?><br/>
                <?= $this->translate('użytkownika') ?>
            </th>
            <th>
                <?= $this->translate('Menu') ?>
                <br/> <?= $this->translate('Klienta') ?>
            </th>
            <th>
                <?= $this->translate("Strona") ?><br/>
                <?= $this->translate("startowa?") ?>
            </th>
            <th>
                <?= $this->translate('Czy') ?><br/>
                <?= $this->translate('ukryte?') ?>
            </th>
            <th><?= $this->translate('Telefon') ?></th>
            <th><?= $this->translate('Tablet') ?></th>
            <th><?= $this->translate('PC') ?></th>
            <th>
                <?= $this->translate('Cookie') ?>
            </th>
            <th><?= $this->translate('Opcje') ?></th>
        </tr>
        </thead>
        <?php foreach ($this->submenu as $k => $m) : ?>
            <tr>
                <td><?= $k + 1 ?></td>
                <td><?= $m->getName() ?></td>
                <td><?= $m->getLabel() ?></td>
                <td><?= $m->getRoute() ?></td>
                <td><?= $m->getRouteParams() ?></td>
                <td><?= $m->getSequence() ?></td>
                <td><?= empty($m->getIcon()) ? '' : $this->fontAwesome($m->getIcon()) ?></td>
                <td><?= $this->chk($m->getIsUserMenu()) ?></td>
                <td><?= $this->chk($m->getIsCustomerMenu()) ?></td>
                <td><?= $this->chk($m->getIsShortcutMenu()) ?></td>
                <td><?= $this->chk($m->getIsHidden()) ?></td>
                <td><?= $this->chk($m->getSettingSmall()) ?></td>
                <td><?= $this->chk($m->getSettingMedium()) ?></td>
                <td><?= $this->chk($m->getSettingLarge()) ?></td>
                <td><?= $m->getCookie() ?></td>
                <td>
                    <a
                            href="<?= $this->url('configuration/subresourceEdit', ['id' => $m->getId()]) ?>"
                            class="subresource-edit"
                    ><?= $this->fontAwesome('pencil') ?></a>
                    <a
                            href="<?= $this->url('configuration/resourcePositions', ['id' => $m->getId()]) ?>"
                            class="resource-edit-position"
                    ><?= $this->fontAwesome('user') ?></a>
                    <a
                            href="<?= $this->url('configuration/submenu', ['id' => $m->getId()]) ?>"
                            class="resource-show-submenu"
                    ><?= $this->fontAwesome('navicon') ?></a>
                </td>
            </tr>
            <tr class="config-details">
                <td colspan="16"></td>
            </tr>
        <?php endforeach ?>
    </table>
</div>