<style>
    .select2-container {
        width: 150px !important;
    }
</style>

<?= $this->partial('users/index/tabs') ?>

<div class="row">
    <div class="col-md-12">
        <?= $this->operations([
            [
                'icon' => 'plus',
                'label' => 'dodaj',
                'route' => 'users/add',
            ],
        ]) ?>
    </div>
</div>

<?= $this->searchForm($this->search, false, 8) ?>

<?= $this->table($this->table, 'users') ?>

<?php
$this->headScript()->appendFile($this->basePath('js/min/user.js'));
$autocompleteValues = $this->json($this->autocomplete_values ?? []);
$this->inlineScript()->captureStart();
echo <<<JS
    $(function() {
        const autocompleteData = {$autocompleteValues};
        new AutocompleteSingle('customer','{$this->url('autocomplete/customer')}', autocompleteData);
        new Autocomplete('position');
        new Autocomplete('region');
        new Autocomplete('supervisor');
        Utils.setActivateEvents();
        const user = new User();
        user.initEvents();
    });
JS;
$this->inlineScript()->captureEnd();
?>