<?php

use Users\Controller\IndexController;
use Users\Controller\LoginController;

$action = $this->urlParam('action');
$controller = $this->urlParam('controller');

echo $this->navigation()->menu()->renderMenu(
    new \Laminas\Navigation\Navigation(
        [
            [
                'label' => $this->translate('Użytkownicy'),
                'uri' => $this->url('users'),
                'active' => $controller == IndexController::class,
            ],
            [
                'label' => $this->translate('Logowanie'),
                'uri' => $this->url('users/login'),
                'active' => $controller == LoginController::class,
            ],
        ]
    ),
    [
        'tabs' => true,
        'page' => true,
        'ulClass' => 'mb-2',
    ]
);