<div class="row">
    <div class="col-md-12">
        <?= $this->operations([
            [
                'icon' => 'plus',
                'label' => 'dodaj',
                'route' => 'assembly-orders/add',
            ],
        ]) ?>
    </div>
</div>

<?= $this->searchForm($this->search) ?>

<?= $this->table($this->table, 'assembly-orders') ?>


<?php
$this->inlineScript()->captureStart();

echo <<<JS
    $(function() {
        new AutocompleteSingle('user')
        new AutocompleteSingle('customer')
        
        $('#assemblyOrdersTable > tbody > tr').click((e) => {
            if ($(e.target).is('td')) {
                window.location.href = $(e.currentTarget).find('a').attr('href')
                return false
            }
        })
    })
JS;
$this->inlineScript()->captureEnd();
?>
