<div class="row">
    <div class="col-md-12">
        <a data-bs-toggle="modal" data-bs-target="#clearModal" class="btn btn-outline-secondary clear-all"><?= $this->fontAwesome('trash') ?> Wyczyść tabelę z ankietami NPS</a>
        <a data-bs-toggle="modal" data-bs-target="#addCsvModal" class="btn btn-outline-secondary import-csv ml-3"><?= $this->fontAwesome('upload') ?> Dodaj plik CSV</a>
    </div>
    <div class="col-md-12 mt-5">
    </div>
</div>

<div class="modal fade" id="clearModal" tabindex="-1" aria-labelledby="clearModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="clearModalLabel">Usuń rekordy</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="alert alert-info" role="alert">
                    <?=$this->translate('Czy na pewno chcesz usunąć wszystkie rekordy?') ?>.
                </div>
            </div>
            <div class="modal-footer mt-3">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i class="fa fa-times"></i> Anuluj</button>
                <a class="btn btn-primary" href="<?= $this->url('nps-ratings/clear') ?>"><i class="fa fa-check"></i> Usuń wszystkie</a>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="addCsvModal" tabindex="-1" aria-labelledby="addCsvModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addCsvModalLabel">Dodaj plik</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="alert alert-info" role="alert">
                    <?=$this->translate('Akceptowane formaty importu danych to: <b>CSV</b>') ?>.
                </div>

                <?php
                    $form->prepare(); 
                    $fileElement = $form->get('csv-file');
                    echo $this->form()->openTag($form);
                ?>

                    <div class="form-element">
                        <?= $this->formFile($fileElement) ?>
                        <?= $this->formElementErrors($fileElement) ?>
                    </div>

                    <div class="modal-footer mt-3">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i class="fa fa-times"></i> Anuluj</button>
                        <button type="submit" class="btn btn-primary add-csv"><i class="fa fa-check"></i> Zapisz do bazy</button>
                    </div>

                <?= $this->form()->closeTag() ?>
            </div>
        </div>
    </div>
</div>

<style>
    .ml-3 {
        margin-left: 3rem;
    }

    .modal-body {
        min-height: auto;
    }
    .modal-body > .close {
        position: absolute;
        top: 0;
        right: 0;
        padding: 0.5rem 0.75rem;
        z-index: 1;
    }

    button.close {
        padding: 0;
        background-color: transparent;
        border: 0;
        -webkit-appearance: none;
    }

    .disabled {
        opacity: 0.3 !important;
    }

</style>

<script>
    $(function () {
        $('.add-csv').attr('disabled', 'disabled'); 
        $('.add-csv').addClass('disabled');
        $("#csv-file").change(function() { 
            var fileName = $("#csv-file");  

            if(fileName.get(0).files.length > 0) {
                $('.add-csv').removeAttr('disabled'); 
                $('.add-csv').removeClass('disabled');
            }
        });

    })
</script>