Configuration\Entity\Resource:
  type: entity
  table: configurationResources
  repositoryClass: Configuration\Repository\ResourceRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      options:
        collation: utf8_polish_ci
    label:
      type: string
      options:
        collation: utf8_polish_ci
    route:
      type: string
      options:
        collation: utf8_polish_ci
    routeParams:
      type: array
      nullable: true
      options:
        collation: utf8_polish_ci
    icon:
      type: string
      nullable: true
      options:
        collation: utf8_polish_ci
    sequence:
      type: smallint
    isUserMenu:
      type: boolean
    isCustomerMenu:
      type: boolean
    isShortcutMenu:
      type: boolean
      options:
        default: false
    isHidden:
      type: boolean
    isUserDetailsMenu:
      type: boolean
    cookie:
      type: string
      nullable: true
    settingSmall:
      type: smallint
    settingMedium:
      type: smallint
    settingLarge:
      type: smallint
  oneToMany:
    subresources:
      targetEntity: Resource
      mappedBy: parent
    resourcePositions:
      targetEntity: ResourcePosition
      mappedBy: resource
  manyToOne:
    parent:
      targetEntity: Resource
      inversedBy: subresources
      joinColumns:
        parentId:
          referencedColumnName: id
  manyToMany:
    objects:
      targetEntity: ObjectGroup
      mappedBy: resources