Configuration\Entity\ResourcePosition:
  type: entity
  table: configurationResourcePositions
  repositoryClass: Configuration\Repository\ResourcePositionRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    settingSmall:
      type: smallint
    settingMedium:
      type: smallint
    settingLarge:
      type: smallint
  manyToOne:
    resource:
      targetEntity: Resource
      inversedBy: resourcePositions
      joinColumns:
        resourceId:
          referencedColumnName: id
    position:
      targetEntity: Position
      inversedBy: resourcePositions
      joinColumns:
        positionId:
          referencedColumnName: id