Configuration\Entity\Position:
  type: entity
  table: configurationPositions
  repositoryClass: Configuration\Repository\PositionRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    key:
      type: string
      column: '`key`'
    name:
      type: string
      options:
        collation: utf8_polish_ci
    isActive:
      type: boolean
  oneToMany:
    resourcePositions:
      targetEntity: ResourcePosition
      mappedBy: position
      cascade: [ 'persist' ]