<?php
$form = new \Laminas\Form\Form();
$form->setAttributes([
    'action'=>'/configuration/saveSequence',
    'method'=>'post',
    'id' => 'editForm',
]);
?>
<?= $this->form()->openTag($form); ?>
<table class="table table-stripped table-hover table-sorted">
    <tbody>
    <?php foreach($this->fields as $field)  : ?>
        <?php if(!empty($field->getLabel())) : ?>
        <tr>
            <td class="handle">
                <span class="fa fa-sort"></span>
                <?php
                   $element = new \Laminas\Form\Element\Hidden(
                        'sequence[]'
                    );
                $element->setValue($field->getId());
                ?>
                <?= $this->formElement($element) ?>
            </td>
            <td>
                <?php
                    $label = new Laminas\Form\Element\Text("label[{$field->getId()}]");
                    $label->setValue($field->getLabel());

                ?>
                <?= $this->formElement($label) ?>
            </td>
        </tr>
        <?php endif; ?>
    <?php endforeach ?>

    </tbody>
</table>
<?= $this->form()->closeTag() ?>
<script>
    $('.table-sorted').sortable({
        containerSelector: 'table',
        itemPath: '> tbody',
        itemSelector: 'tr',
        handle: '.handle',
        placeholder: '<tr class="placeholder"/>'
    });
</script>