<br /><br />
<div class="ajax-data">

    <?php if (count($object->getFields())) : ?>
        <?php
        $form = new \Laminas\Form\Form();
        $form->setAttribute('action', '/configuration/saveVisibility/' . $object->getId());
        $form->setAttribute('method', 'POST');
        $form->setAttribute('id', 'editForm');
        $form->setAttribute('name', 'editForm');
        ?>
        <?= $this->form()->openTag($form)?>
        <div style="position:absolute; left:0; right:0; top: 0; bottom: 50px; overflow:scroll; margin: 0px auto">
            <table class ="table table-condensed table-hover">
                    <thead>
                        <tr>
                            <th><?= $this->translate('Pole') ?></th>
                        <?php foreach($this->positions as $position) : ?>
                                <th><?= $position->getName() ?></th>
                        <?php endforeach; ?>
                        </tr>
                    </thead>
                <tbody>
                <?php foreach ($this->object->getFields() as $i => $field) : ?>
                    <tr class="config-tr-border">
                        <?php
                         if (empty($field->getLabel()))  {
                             continue;
                         }
                        ?>
                        <td><?= $field->getLabel() ?>
                            <?php
                            $elementdefault = new \Laminas\Form\Element\Select(
                                'answers[' . $field->getId() . '][' . $position->getId() . '][small]',
                                [

                                    'value_options' => [
                                        \Configuration\Entity\ObjectFieldDetail::SETTING_NO => \Configuration\Entity\ObjectFieldDetail::getSettings()[\Configuration\Entity\ObjectFieldDetail::SETTING_NO],
                                        \Configuration\Entity\ObjectFieldDetail::SETTING_VIEW => \Configuration\Entity\ObjectFieldDetail::getSettings()[\Configuration\Entity\ObjectFieldDetail::SETTING_VIEW],
                                        \Configuration\Entity\ObjectFieldDetail::SETTING_SAVE => \Configuration\Entity\ObjectFieldDetail::getSettings()[\Configuration\Entity\ObjectFieldDetail::SETTING_SAVE],
                                        \Configuration\Entity\ObjectFieldDetail::SETTING_ADD => \Configuration\Entity\ObjectFieldDetail::getSettings()[\Configuration\Entity\ObjectFieldDetail::SETTING_ADD],
                                        \Configuration\Entity\ObjectFieldDetail::SETTING_SAVE_ADD_NOT_EMPTY => \Configuration\Entity\ObjectFieldDetail::getSettings()[\Configuration\Entity\ObjectFieldDetail::SETTING_SAVE_ADD_NOT_EMPTY],
                                        \Configuration\Entity\ObjectFieldDetail::SETTING_SAVE_NOT_EMPTY => \Configuration\Entity\ObjectFieldDetail::getSettings()[\Configuration\Entity\ObjectFieldDetail::SETTING_SAVE_NOT_EMPTY],

                                    ]
                                ]
                            );
                            $elementdefault->setAttribute('class', 'input-sm input-custom-small');
                            $elementdefault->setAttribute('class', 'set-default-values');

                            ?>
                            <?= '<br />' ?>
                            <?= $this->formElement($elementdefault); ?>
                        </td>
                        <?php foreach ($this->positions as $position) : ?>
                            <td class="no-padding config-td-border">
                                <?php
                                    $element = new \Laminas\Form\Element\Select(
                                        'answers[' . $field->getId() . '][' . $position->getId() . '][small]',
                                        [

                                            'value_options' => [
                                                \Configuration\Entity\ObjectFieldDetail::SETTING_NO => \Configuration\Entity\ObjectFieldDetail::getSettings()[\Configuration\Entity\ObjectFieldDetail::SETTING_NO],
                                                \Configuration\Entity\ObjectFieldDetail::SETTING_VIEW => \Configuration\Entity\ObjectFieldDetail::getSettings()[\Configuration\Entity\ObjectFieldDetail::SETTING_VIEW],
                                                \Configuration\Entity\ObjectFieldDetail::SETTING_SAVE => \Configuration\Entity\ObjectFieldDetail::getSettings()[\Configuration\Entity\ObjectFieldDetail::SETTING_SAVE],
                                                \Configuration\Entity\ObjectFieldDetail::SETTING_ADD => \Configuration\Entity\ObjectFieldDetail::getSettings()[\Configuration\Entity\ObjectFieldDetail::SETTING_ADD],
                                                \Configuration\Entity\ObjectFieldDetail::SETTING_SAVE_ADD_NOT_EMPTY => \Configuration\Entity\ObjectFieldDetail::getSettings()[\Configuration\Entity\ObjectFieldDetail::SETTING_SAVE_ADD_NOT_EMPTY],
                                                \Configuration\Entity\ObjectFieldDetail::SETTING_SAVE_NOT_EMPTY => \Configuration\Entity\ObjectFieldDetail::getSettings()[\Configuration\Entity\ObjectFieldDetail::SETTING_SAVE_NOT_EMPTY],

                                            ]
                                        ]
                                    );
                                    if (!empty($data[$field->getId()][$position->getId()]['small'])){
                                        $element->setValue($data[$field->getId()][$position->getId()]['small']);
                                    }
                                ?>

                                <?php
                                    $elementMedium = new \Laminas\Form\Element\Select(
                                        'answers[' . $field->getId() . '][' . $position->getId() . '][medium]',
                                        [

                                            'value_options' => [
                                                \Configuration\Entity\ObjectFieldDetail::SETTING_NO => \Configuration\Entity\ObjectFieldDetail::getSettings()[\Configuration\Entity\ObjectFieldDetail::SETTING_NO],
                                                \Configuration\Entity\ObjectFieldDetail::SETTING_VIEW => \Configuration\Entity\ObjectFieldDetail::getSettings()[\Configuration\Entity\ObjectFieldDetail::SETTING_VIEW],
                                                \Configuration\Entity\ObjectFieldDetail::SETTING_SAVE => \Configuration\Entity\ObjectFieldDetail::getSettings()[\Configuration\Entity\ObjectFieldDetail::SETTING_SAVE],
                                                \Configuration\Entity\ObjectFieldDetail::SETTING_ADD => \Configuration\Entity\ObjectFieldDetail::getSettings()[\Configuration\Entity\ObjectFieldDetail::SETTING_ADD],
                                                \Configuration\Entity\ObjectFieldDetail::SETTING_SAVE_ADD_NOT_EMPTY => \Configuration\Entity\ObjectFieldDetail::getSettings()[\Configuration\Entity\ObjectFieldDetail::SETTING_SAVE_ADD_NOT_EMPTY],
                                                \Configuration\Entity\ObjectFieldDetail::SETTING_SAVE_NOT_EMPTY => \Configuration\Entity\ObjectFieldDetail::getSettings()[\Configuration\Entity\ObjectFieldDetail::SETTING_SAVE_NOT_EMPTY],
                                            ]
                                        ]
                                    );
                                    if (!empty($data[$field->getId()][$position->getId()]['medium'])){
                                        $elementMedium->setValue($data[$field->getId()][$position->getId()]['medium']);
                                    }
                                ?>
                                <?php
                                    $elementLarge = new \Laminas\Form\Element\Select(
                                        'answers[' . $field->getId() . '][' . $position->getId() . '][large]',
                                        [
                                            'value_options' => [
                                                \Configuration\Entity\ObjectFieldDetail::SETTING_NO => \Configuration\Entity\ObjectFieldDetail::getSettings()[\Configuration\Entity\ObjectFieldDetail::SETTING_NO],
                                                \Configuration\Entity\ObjectFieldDetail::SETTING_VIEW => \Configuration\Entity\ObjectFieldDetail::getSettings()[\Configuration\Entity\ObjectFieldDetail::SETTING_VIEW],
                                                \Configuration\Entity\ObjectFieldDetail::SETTING_SAVE => \Configuration\Entity\ObjectFieldDetail::getSettings()[\Configuration\Entity\ObjectFieldDetail::SETTING_SAVE],
                                                \Configuration\Entity\ObjectFieldDetail::SETTING_ADD => \Configuration\Entity\ObjectFieldDetail::getSettings()[\Configuration\Entity\ObjectFieldDetail::SETTING_ADD],
                                                \Configuration\Entity\ObjectFieldDetail::SETTING_SAVE_ADD_NOT_EMPTY => \Configuration\Entity\ObjectFieldDetail::getSettings()[\Configuration\Entity\ObjectFieldDetail::SETTING_SAVE_ADD_NOT_EMPTY],
                                                \Configuration\Entity\ObjectFieldDetail::SETTING_SAVE_NOT_EMPTY => \Configuration\Entity\ObjectFieldDetail::getSettings()[\Configuration\Entity\ObjectFieldDetail::SETTING_SAVE_NOT_EMPTY],
                                            ]
                                        ]
                                    );
                                    $element->setAttribute('class', 'input-sm input-custom-small');
                                    $elementLarge->setAttribute('class', 'input-sm input-custom-small');
                                    $elementMedium->setAttribute('class', 'input-sm input-custom-small');
                                    if (!empty($data[$field->getId()][$position->getId()]['large'])){
                                        $elementLarge->setValue($data[$field->getId()][$position->getId()]['large']);
                                    }
                                ?>
                                <table>
                                    <tr>
                                        <td class="no-padding"><i class="fa fa-mobile" aria-hidden="true"></i></td>
                                        <td class="no-padding"><?= $this->formElement($element); ?></td>
                                    </tr>
                                    <tr>
                                        <td class="no-padding"><i class="fa fa-tablet fa-1x" aria-hidden="true"></i></td>
                                        <td class="no-padding"><?= $this->formElement($elementMedium); ?></td>
                                    </tr>
                                    <tr>
                                        <td class="no-padding"><i class="fa fa-desktop" aria-hidden="true"></i></td>
                                        <td class="no-padding"><?= $this->formElement($elementLarge); ?></td>
                                    </tr>
                                </table>
                            </td>
                        <?php endforeach ?>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        </div>
        <?php
            $submit = new \Laminas\Form\Element\Submit();
            $submit->setValue($this->translate("Zapisz"));
            $submit->setAttributes(['type' => 'submit', 'class' => 'btn btn-sl form-save', 'name' => 'submit']);

            $cancel = new \Laminas\Form\Element\Button();
            $cancel->setValue('Zamknij');
            $cancel->setAttributes(['class'=> 'form-close btn btn-default', 'name' => 'cancel']);
        ?>
        <div style="padding: 10px; position:fixed; bottom: 10px; right: 10px">
            <?= $this->formElement($cancel)?> <?= $this->formElement($submit) ?>
        </div>
        <?= $this->form()->closeTag($form); ?>
    <?php endif; ?>
</div>



